const forbiddenNames = [
    {
        id: 1,
        english: "Al-Ahad",
        arabic: "الأحد",
        urdu: "الاحد",
        persian: "الاحد",
        meaning: "The One (Name of Allah)",
        origin: "Arabic",
        pronunciation: "Al-Aa-had",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 2,
        english: "Al-Khaliq",
        arabic: "الخالق",
        urdu: "الخالق",
        persian: "الخالق",
        meaning: "The Creator (Name of Allah)",
        origin: "Arabic",
        pronunciation: "Al-Khaa-liq",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 3,
        english: "Malik al-Mulk",
        arabic: "مالك الملك",
        urdu: "مالک الملک",
        persian: "مالک الملک",
        meaning: "Owner of Sovereignty (Name of Allah)",
        origin: "Arabic",
        pronunciation: "Maa-lik al-Mulk",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 4,
        english: "Ar-Rahman",
        arabic: "الرحمن",
        urdu: "الرحمن",
        persian: "الرحمن",
        meaning: "The Most Gracious (Name of Allah)",
        origin: "Arabic",
        pronunciation: "Ar-Rah-maan",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 5,
        english: "Al-Malik",
        arabic: "الملك",
        urdu: "الملک",
        persian: "الملک",
        meaning: "The King (Name of Allah)",
        origin: "Arabic",
        pronunciation: "Al-Ma-lik",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 6,
        english: "Ar-Razzaq",
        arabic: "الرزاق",
        urdu: "الرزاق",
        persian: "الرزاق",
        meaning: "The Provider (Name of Allah)",
        origin: "Arabic",
        pronunciation: "Ar-Raz-zaq",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 7,
        english: "Al-Muhaimin",
        arabic: "المهيمن",
        urdu: "المهیمن",
        persian: "المهیمن",
        meaning: "The Protector (Name of Allah)",
        origin: "Arabic",
        pronunciation: "Al-Mu-hai-min",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 8,
        english: "Al-Jabbar",
        arabic: "الجبار",
        urdu: "الجبار",
        persian: "الجبار",
        meaning: "The Compeller (Name of Allah)",
        origin: "Arabic",
        pronunciation: "Al-Jab-bar",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 9,
        english: "Al-Mutakabbir",
        arabic: "المتكبر",
        urdu: "المتکبر",
        persian: "المتکبر",
        meaning: "The Supreme (Name of Allah)",
        origin: "Arabic",
        pronunciation: "Al-Mu-ta-kab-bir",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 10,
        english: "Al-Quddus",
        arabic: "القدوس",
        urdu: "القدوس",
        persian: "القدوس",
        meaning: "The Holy (Name of Allah)",
        origin: "Arabic",
        pronunciation: "Al-Qud-doos",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 11,
        english: "As-Salam",
        arabic: "السلام",
        urdu: "السلام",
        persian: "السلام",
        meaning: "The Source of Peace (Name of Allah)",
        origin: "Arabic",
        pronunciation: "As-Sa-laam",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 12,
        english: "Al-Mu'min",
        arabic: "المؤمن",
        urdu: "المؤمن",
        persian: "المؤمن",
        meaning: "The Guardian of Faith (Name of Allah)",
        origin: "Arabic",
        pronunciation: "Al-Mu-min",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 13,
        english: "Al-Muhsi",
        arabic: "المحصي",
        urdu: "المحصی",
        persian: "المحصی",
        meaning: "The Reckoner (Name of Allah)",
        origin: "Arabic",
        pronunciation: "Al-Muh-see",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 14,
        english: "Al-Mubdi",
        arabic: "المبدئ",
        urdu: "المبدئ",
        persian: "المبدئ",
        meaning: "The Originator (Name of Allah)",
        origin: "Arabic",
        pronunciation: "Al-Mub-dee",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 15,
        english: "Al-Mu'id",
        arabic: "المعيد",
        urdu: "المعید",
        persian: "المعید",
        meaning: "The Restorer (Name of Allah)",
        origin: "Arabic",
        pronunciation: "Al-Mu-eed",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 16,
        english: "Al-Muhyi",
        arabic: "المحيي",
        urdu: "المحیی",
        persian: "المحیی",
        meaning: "The Giver of Life (Name of Allah)",
        origin: "Arabic",
        pronunciation: "Al-Muh-yee",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 17,
        english: "Al-Mumit",
        arabic: "المميت",
        urdu: "الممیت",
        persian: "الممیت",
        meaning: "The Bringer of Death (Name of Allah)",
        origin: "Arabic",
        pronunciation: "Al-Mu-meet",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 18,
        english: "Al-Hayy",
        arabic: "الحي",
        urdu: "الحی",
        persian: "الحی",
        meaning: "The Ever-Living (Name of Allah)",
        origin: "Arabic",
        pronunciation: "Al-Hayy",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 19,
        english: "Al-Qayyum",
        arabic: "القيوم",
        urdu: "القیوم",
        persian: "القیوم",
        meaning: "The Sustainer (Name of Allah)",
        origin: "Arabic",
        pronunciation: "Al-Qay-yoom",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 20,
        english: "Al-Mu'izz",
        arabic: "المعز",
        urdu: "المعز",
        persian: "المعز",
        meaning: "The Honorer (Name of Allah)",
        origin: "Arabic",
        pronunciation: "Al-Mu-izz",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 21,
        english: "Al-Mudhill",
        arabic: "المذل",
        urdu: "المذل",
        persian: "المذل",
        meaning: "The Dishonorer (Name of Allah)",
        origin: "Arabic",
        pronunciation: "Al-Mud-hill",
        gender: "boy",
        status: "forbidden",
        quranic: false
    }
];
