const forbiddenNames = [
    {
        id: 1,
        english: "Abdul Nabi",
        arabic: "عبد النبي",
        urdu: "عبد النبی",
        persian: "عبد النبی",
        meaning: "Servant of the Prophet",
        origin: "Arabic",
        pronunciation: "Ab-dul Na-bee",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 2,
        english: "Abdul Rasool",
        arabic: "عبد الرسول",
        urdu: "عبد الرسول",
        persian: "عبد الرسول",
        meaning: "Servant of the Messenger",
        origin: "Arabic",
        pronunciation: "Ab-dul Ra-sool",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 3,
        english: "Abdul Maseeh",
        arabic: "عبد المسيح",
        urdu: "عبد المسیح",
        persian: "عبد المسیح",
        meaning: "Servant of the Messiah",
        origin: "Arabic",
        pronunciation: "Ab-dul Ma-seeh",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 4,
        english: "Abdul Ka'bah",
        arabic: "عبد الكعبة",
        urdu: "عبد کعبہ",
        persian: "عبد کعبه",
        meaning: "Servant of the Kaaba",
        origin: "Arabic",
        pronunciation: "Ab-dul Ka-bah",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 5,
        english: "Abdul Husayn",
        arabic: "عبد الحسين",
        urdu: "عبد حسین",
        persian: "عبد حسین",
        meaning: "Servant of Husayn",
        origin: "Arabic",
        pronunciation: "Ab-dul Hu-sayn",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 6,
        english: "Abdul Uzza",
        arabic: "عبد العزى",
        urdu: "عبد العزی",
        persian: "عبد العزی",
        meaning: "Servant of the idol al-Uzza",
        origin: "Arabic",
        pronunciation: "Ab-dul Uz-za",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 7,
        english: "Abdul Dar",
        arabic: "عبد الدار",
        urdu: "عبد الدار",
        persian: "عبد الدار",
        meaning: "Servant of the house",
        origin: "Arabic",
        pronunciation: "Ab-dul Daar",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 8,
        english: "Abdul Ali",
        arabic: "عبد علي",
        urdu: "عبد علی",
        persian: "عبد علی",
        meaning: "Servant of Ali (if meant as person)",
        origin: "Arabic",
        pronunciation: "Ab-dul A-lee",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 9,
        english: "Abdul Zahra",
        arabic: "عبد الزهراء",
        urdu: "عبد الزہرا",
        persian: "عبد الزهرا",
        meaning: "Servant of Fatimah Zahra",
        origin: "Arabic",
        pronunciation: "Ab-dul Zah-ra",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 10,
        english: "Abdul Qamar",
        arabic: "عبد القمر",
        urdu: "عبد القمر",
        persian: "عبد قمر",
        meaning: "Servant of the moon",
        origin: "Arabic",
        pronunciation: "Ab-dul Qa-mar",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 11,
        english: "Ar-Rahman",
        arabic: "الرحمن",
        urdu: "الرحمن",
        persian: "الرحمن",
        meaning: "The Most Merciful (Allah's name only)",
        origin: "Arabic",
        pronunciation: "Ar-Rah-maan",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 12,
        english: "Al-Khaliq",
        arabic: "الخالق",
        urdu: "الخالق",
        persian: "الخالق",
        meaning: "The Creator",
        origin: "Arabic",
        pronunciation: "Al-Khaa-liq",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 13,
        english: "Al-Jabbar",
        arabic: "الجبار",
        urdu: "الجبار",
        persian: "الجبار",
        meaning: "The Compeller",
        origin: "Arabic",
        pronunciation: "Al-Jab-baar",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 14,
        english: "Al-Qahhar",
        arabic: "القهار",
        urdu: "القهار",
        persian: "القهار",
        meaning: "The Subduer",
        origin: "Arabic",
        pronunciation: "Al-Qah-haar",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 15,
        english: "Al-Mutakabbir",
        arabic: "المتكبر",
        urdu: "المتکبر",
        persian: "المتکبر",
        meaning: "The Supreme",
        origin: "Arabic",
        pronunciation: "Al-Mu-ta-kab-bir",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 16,
        english: "Al-Ahad",
        arabic: "الأحد",
        urdu: "الاحد",
        persian: "الاحد",
        meaning: "The One",
        origin: "Arabic",
        pronunciation: "Al-Aa-had",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 17,
        english: "Al-Samad",
        arabic: "الصمد",
        urdu: "الصمد",
        persian: "الصمد",
        meaning: "The Eternal",
        origin: "Arabic",
        pronunciation: "As-Sa-mad",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 18,
        english: "Al-Bari",
        arabic: "البارئ",
        urdu: "البارئ",
        persian: "البارئ",
        meaning: "The Evolver",
        origin: "Arabic",
        pronunciation: "Al-Baa-ri",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 19,
        english: "Al-Malik",
        arabic: "الملك",
        urdu: "الملک",
        persian: "الملک",
        meaning: "The King (if used alone arrogantly)",
        origin: "Arabic",
        pronunciation: "Al-Ma-lik",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 20,
        english: "Al-Awwal",
        arabic: "الأول",
        urdu: "الاول",
        persian: "الاول",
        meaning: "The First (exclusive to Allah)",
        origin: "Arabic",
        pronunciation: "Al-Aw-wal",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 21,
        english: "Lat",
        arabic: "اللات",
        urdu: "لات",
        persian: "لات",
        meaning: "Pagan goddess of Arabs",
        origin: "Arabic",
        pronunciation: "Laat",
        gender: "girl",
        status: "forbidden",
        quranic: false
    },
    {
        id: 22,
        english: "Uzza",
        arabic: "العزى",
        urdu: "عزی",
        persian: "عزی",
        meaning: "Idol worshipped in Jahiliyyah",
        origin: "Arabic",
        pronunciation: "Uz-za",
        gender: "girl",
        status: "forbidden",
        quranic: false
    },
    {
        id: 23,
        english: "Manat",
        arabic: "مناة",
        urdu: "منات",
        persian: "منات",
        meaning: "Idol of destiny",
        origin: "Arabic",
        pronunciation: "Ma-naat",
        gender: "girl",
        status: "forbidden",
        quranic: false
    },
    {
        id: 24,
        english: "Hubal",
        arabic: "هبل",
        urdu: "ہبل",
        persian: "هبل",
        meaning: "Idol in Makkah",
        origin: "Arabic",
        pronunciation: "Hu-bal",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 25,
        english: "Baal",
        arabic: "بعل",
        urdu: "بعل",
        persian: "بعل",
        meaning: "Idol from ancient times",
        origin: "Arabic",
        pronunciation: "Ba-al",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 26,
        english: "Wadd",
        arabic: "ود",
        urdu: "ود",
        persian: "ود",
        meaning: "Idol of Prophet Nuh's people",
        origin: "Arabic",
        pronunciation: "Wadd",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 27,
        english: "Suwa",
        arabic: "سواع",
        urdu: "سواع",
        persian: "سواع",
        meaning: "Idol of Nuh's people",
        origin: "Arabic",
        pronunciation: "Su-wa",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 28,
        english: "Yaghuth",
        arabic: "يغوث",
        urdu: "یغوث",
        persian: "یغوث",
        meaning: "Idol of Nuh's people",
        origin: "Arabic",
        pronunciation: "Ya-ghooth",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 29,
        english: "Yauq",
        arabic: "يعوق",
        urdu: "یعوق",
        persian: "یعوق",
        meaning: "Idol of Nuh's people",
        origin: "Arabic",
        pronunciation: "Ya-ooq",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 30,
        english: "Nasr",
        arabic: "نسر",
        urdu: "نسر",
        persian: "نسر",
        meaning: "Idol of Nuh's people",
        origin: "Arabic",
        pronunciation: "Nasr",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 31,
        english: "Iblis",
        arabic: "إبليس",
        urdu: "ابلیس",
        persian: "ابلیس",
        meaning: "The Devil",
        origin: "Arabic",
        pronunciation: "Ib-lees",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 32,
        english: "Khinzab",
        arabic: "خنزب",
        urdu: "خنزب",
        persian: "خنزب",
        meaning: "Devil distracting in prayer",
        origin: "Arabic",
        pronunciation: "Khin-zab",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 33,
        english: "Dasim",
        arabic: "داسم",
        urdu: "داسم",
        persian: "داسم",
        meaning: "Devil causing family disputes",
        origin: "Arabic",
        pronunciation: "Da-sim",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 34,
        english: "Awar",
        arabic: "أعور",
        urdu: "اعور",
        persian: "اعور",
        meaning: "Devil who tempts people",
        origin: "Arabic",
        pronunciation: "A-war",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 35,
        english: "Zalanbur",
        arabic: "زلنبور",
        urdu: "زلنبور",
        persian: "زلنبور",
        meaning: "Devil of markets",
        origin: "Arabic",
        pronunciation: "Za-lan-bur",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 36,
        english: "Walhan",
        arabic: "ولهان",
        urdu: "ولهان",
        persian: "ولهان",
        meaning: "Devil causing doubts",
        origin: "Arabic",
        pronunciation: "Wal-han",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 37,
        english: "Qarin",
        arabic: "قرين",
        urdu: "قرین",
        persian: "قرین",
        meaning: "Evil companion jinn",
        origin: "Arabic",
        pronunciation: "Qa-reen",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 38,
        english: "Abyad",
        arabic: "أبيض",
        urdu: "ابیض",
        persian: "ابیض",
        meaning: "Satan of deception",
        origin: "Arabic",
        pronunciation: "Ab-yad",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 39,
        english: "Maskhun",
        arabic: "مسخون",
        urdu: "مسخون",
        persian: "مسخون",
        meaning: "Mentioned among devils in tafsir",
        origin: "Arabic",
        pronunciation: "Mas-khoon",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 40,
        english: "Lahab",
        arabic: "لهب",
        urdu: "لہب",
        persian: "لهب",
        meaning: "From Abu Lahab - flame, enemy of Islam",
        origin: "Arabic",
        pronunciation: "La-hab",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 41,
        english: "Fir'awn",
        arabic: "فرعون",
        urdu: "فرعون",
        persian: "فرعون",
        meaning: "Pharaoh",
        origin: "Arabic",
        pronunciation: "Fir-awn",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 42,
        english: "Haman",
        arabic: "هامان",
        urdu: "ہامان",
        persian: "هامان",
        meaning: "Minister of Pharaoh",
        origin: "Arabic",
        pronunciation: "Ha-maan",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 43,
        english: "Qarun",
        arabic: "قارون",
        urdu: "قارون",
        persian: "قارون",
        meaning: "Arrogant rich man (Korah)",
        origin: "Arabic",
        pronunciation: "Qa-roon",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 44,
        english: "Namrud",
        arabic: "نمرود",
        urdu: "نمرود",
        persian: "نمرود",
        meaning: "King who opposed Prophet Ibrahim",
        origin: "Arabic",
        pronunciation: "Nam-rood",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 45,
        english: "Abu Jahl",
        arabic: "أبو جهل",
        urdu: "ابوجہل",
        persian: "ابوجهل",
        meaning: "Ignorant enemy of Islam",
        origin: "Arabic",
        pronunciation: "A-boo Jahal",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 46,
        english: "Abu Lahab",
        arabic: "أبو لهب",
        urdu: "ابولہب",
        persian: "ابولهب",
        meaning: "Cursed in Quran",
        origin: "Arabic",
        pronunciation: "A-boo La-hab",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 47,
        english: "Yazid",
        arabic: "يزيد",
        urdu: "یزید",
        persian: "یزید",
        meaning: "Tyrant (controversial historical)",
        origin: "Arabic",
        pronunciation: "Ya-zeed",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 48,
        english: "Shaddad",
        arabic: "شداد",
        urdu: "شداد",
        persian: "شداد",
        meaning: "Oppressive king",
        origin: "Arabic",
        pronunciation: "Shad-daad",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 49,
        english: "Jaban",
        arabic: "جبان",
        urdu: "جبان",
        persian: "جبان",
        meaning: "Coward",
        origin: "Arabic",
        pronunciation: "Ja-baan",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 50,
        english: "Zulm",
        arabic: "ظلم",
        urdu: "ظلم",
        persian: "ظلم",
        meaning: "Means oppression itself",
        origin: "Arabic",
        pronunciation: "Zulm",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 51,
        english: "Harb",
        arabic: "حرب",
        urdu: "حرب",
        persian: "حرب",
        meaning: "War",
        origin: "Arabic",
        pronunciation: "Harb",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 52,
        english: "Himar",
        arabic: "حمار",
        urdu: "حمار",
        persian: "حمار",
        meaning: "Donkey",
        origin: "Arabic",
        pronunciation: "Hi-maar",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 53,
        english: "Kalb",
        arabic: "كلب",
        urdu: "کلب",
        persian: "کلب",
        meaning: "Dog",
        origin: "Arabic",
        pronunciation: "Kalb",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 54,
        english: "Fasiq",
        arabic: "فاسق",
        urdu: "فاسق",
        persian: "فاسق",
        meaning: "Disobedient, sinner",
        origin: "Arabic",
        pronunciation: "Faa-siq",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 55,
        english: "Zalim",
        arabic: "ظالم",
        urdu: "ظالم",
        persian: "ظالم",
        meaning: "Oppressor",
        origin: "Arabic",
        pronunciation: "Zaa-lim",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 56,
        english: "Shaitan",
        arabic: "شيطان",
        urdu: "شیطان",
        persian: "شیطان",
        meaning: "Devil",
        origin: "Arabic",
        pronunciation: "Shai-taan",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 57,
        english: "Dhib",
        arabic: "ذئب",
        urdu: "ذئب",
        persian: "ذئب",
        meaning: "Wolf",
        origin: "Arabic",
        pronunciation: "Dhi-b",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 58,
        english: "Fasad",
        arabic: "فساد",
        urdu: "فساد",
        persian: "فساد",
        meaning: "Corruption",
        origin: "Arabic",
        pronunciation: "Fa-saad",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 59,
        english: "Su",
        arabic: "سوء",
        urdu: "سوء",
        persian: "سوء",
        meaning: "Evil",
        origin: "Arabic",
        pronunciation: "Soo",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 60,
        english: "Mushrik",
        arabic: "مشرك",
        urdu: "مشرک",
        persian: "مشرک",
        meaning: "Idolater",
        origin: "Arabic",
        pronunciation: "Mush-rik",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 61,
        english: "Malik al-Muluk",
        arabic: "مالك الملوك",
        urdu: "مالک الملوک",
        persian: "مالک الملوک",
        meaning: "King of Kings (Hadith: forbidden)",
        origin: "Arabic",
        pronunciation: "Maa-lik al-Mu-look",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 62,
        english: "Shahanshah",
        arabic: "شاهنشاه",
        urdu: "شاہنشاہ",
        persian: "شاهنشاه",
        meaning: "King of Kings",
        origin: "Persian",
        pronunciation: "Sha-han-shah",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 63,
        english: "Sayyid al-Nas",
        arabic: "سيد الناس",
        urdu: "سید الناس",
        persian: "سید الناس",
        meaning: "Master of people",
        origin: "Arabic",
        pronunciation: "Say-yid an-Naas",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 64,
        english: "Rabb al-Alamin",
        arabic: "رب العالمين",
        urdu: "رب العالمین",
        persian: "رب العالمین",
        meaning: "Lord of the worlds",
        origin: "Arabic",
        pronunciation: "Rab-bul Aa-la-meen",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 65,
        english: "Jannati",
        arabic: "جنتی",
        urdu: "جنتی",
        persian: "جنتی",
        meaning: "Of Paradise (claiming Heaven)",
        origin: "Arabic",
        pronunciation: "Jan-na-ti",
        gender: "both",
        status: "forbidden",
        quranic: false
    },
    {
        id: 66,
        english: "Malak",
        arabic: "ملك",
        urdu: "ملک",
        persian: "ملک",
        meaning: "Angel (if implying real angel)",
        origin: "Arabic",
        pronunciation: "Ma-lak",
        gender: "both",
        status: "forbidden",
        quranic: false
    },
    {
        id: 67,
        english: "Nabi",
        arabic: "نبي",
        urdu: "نبی",
        persian: "نبی",
        meaning: "Prophet",
        origin: "Arabic",
        pronunciation: "Na-bee",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 68,
        english: "Rasool",
        arabic: "رسول",
        urdu: "رسول",
        persian: "رسول",
        meaning: "Messenger",
        origin: "Arabic",
        pronunciation: "Ra-sool",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 69,
        english: "Allahdad",
        arabic: "الله داد",
        urdu: "اللہ داد",
        persian: "الله داد",
        meaning: "Gift of Allah (can mislead)",
        origin: "Persian",
        pronunciation: "Al-lah-daad",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 70,
        english: "NurAllah",
        arabic: "نور الله",
        urdu: "نور اللہ",
        persian: "نور الله",
        meaning: "Light of Allah (if implying divinity)",
        origin: "Arabic",
        pronunciation: "Noor-ul-lah",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 71,
        english: "Shaitan Khan",
        arabic: "شيطان خان",
        urdu: "شیطان خان",
        persian: "شیطان خان",
        meaning: "Mocking combination",
        origin: "Arabic/Urdu",
        pronunciation: "Shai-taan Khaan",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 72,
        english: "Jibreel Khan",
        arabic: "جبريل خان",
        urdu: "جبریل خان",
        persian: "جبریل خان",
        meaning: "Angel name used mockingly",
        origin: "Arabic/Urdu",
        pronunciation: "Jib-reel Khaan",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 73,
        english: "Dunya",
        arabic: "دنیا",
        urdu: "دنیا",
        persian: "دنیا",
        meaning: "World (materialistic meaning)",
        origin: "Arabic",
        pronunciation: "Dun-ya",
        gender: "girl",
        status: "forbidden",
        quranic: false
    },
    {
        id: 74,
        english: "Fitna",
        arabic: "فتنة",
        urdu: "فتنہ",
        persian: "فتنه",
        meaning: "Temptation",
        origin: "Arabic",
        pronunciation: "Fit-na",
        gender: "girl",
        status: "forbidden",
        quranic: false
    },
    {
        id: 75,
        english: "Huzn",
        arabic: "حزن",
        urdu: "حزن",
        persian: "حزن",
        meaning: "Sadness (Prophet ﷺ changed such names)",
        origin: "Arabic",
        pronunciation: "Huzn",
        gender: "both",
        status: "forbidden",
        quranic: false
    },
    {
        id: 76,
        english: "Aasiyah",
        arabic: "عاصية",
        urdu: "عاصیہ",
        persian: "عاصیه",
        meaning: "Disobedient (except Pharaoh's wife's context)",
        origin: "Arabic",
        pronunciation: "Aa-si-yah",
        gender: "girl",
        status: "forbidden",
        quranic: false
    },
    {
        id: 77,
        english: "Barra",
        arabic: "برة",
        urdu: "برہ",
        persian: "بره",
        meaning: "Pious (Prophet ﷺ disliked self-praise names)",
        origin: "Arabic",
        pronunciation: "Bar-ra",
        gender: "girl",
        status: "forbidden",
        quranic: false
    },
    {
        id: 78,
        english: "Yasir Allah",
        arabic: "يسير الله",
        urdu: "یسیر اللہ",
        persian: "یسیر الله",
        meaning: "Improper composition",
        origin: "Arabic",
        pronunciation: "Ya-seer ul-lah",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 79,
        english: "Sultan Allah",
        arabic: "سلطان الله",
        urdu: "سلطان اللہ",
        persian: "سلطان الله",
        meaning: "Arrogant style",
        origin: "Arabic",
        pronunciation: "Sul-taan ul-lah",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 80,
        english: "Hakim-ul-Hukama",
        arabic: "حكيم الحكما",
        urdu: "حکیم الحکما",
        persian: "حکیم الحکما",
        meaning: "Judge of judges (forbidden by hadith)",
        origin: "Arabic",
        pronunciation: "Ha-keem ul-Hu-ka-ma",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 81,
        english: "Fakhri",
        arabic: "فخري",
        urdu: "فخری",
        persian: "فخری",
        meaning: "My pride",
        origin: "Arabic",
        pronunciation: "Fakh-ri",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 82,
        english: "Mutakabbir",
        arabic: "متكبر",
        urdu: "متکبر",
        persian: "متکبر",
        meaning: "The Proud (Allah's attribute)",
        origin: "Arabic",
        pronunciation: "Mu-ta-kab-bir",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 83,
        english: "Ghalibuddin",
        arabic: "غالب الدين",
        urdu: "غالب الدین",
        persian: "غالب الدین",
        meaning: "Victorious religion (exaggeration)",
        origin: "Arabic",
        pronunciation: "Ghaa-lib ud-deen",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 84,
        english: "Sadiq-ul-Akbar",
        arabic: "صديق الأكبر",
        urdu: "صدیق الاکبر",
        persian: "صديق الأكبر",
        meaning: "Only for Abu Bakr (title, not name)",
        origin: "Arabic",
        pronunciation: "Sa-deeq ul-Ak-bar",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 85,
        english: "Amir al-Mu'minin",
        arabic: "أمير المؤمنين",
        urdu: "امیر المؤمنین",
        persian: "امیر المؤمنین",
        meaning: "Leader of the believers (title only)",
        origin: "Arabic",
        pronunciation: "A-meer al-Mu-mi-neen",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 86,
        english: "Nur-e-Khuda",
        arabic: "نور خدا",
        urdu: "نور خدا",
        persian: "نور خدا",
        meaning: "Light of God (theologically dangerous)",
        origin: "Persian",
        pronunciation: "Noor-e-Khu-da",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 87,
        english: "Rahmanullah",
        arabic: "رحمن الله",
        urdu: "رحمن اللہ",
        persian: "رحمن الله",
        meaning: "Mixing divine names",
        origin: "Arabic",
        pronunciation: "Rah-maan ul-lah",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 88,
        english: "Azazil",
        arabic: "عزازيل",
        urdu: "عزازیل",
        persian: "عزازیل",
        meaning: "Name of Iblis before fall",
        origin: "Arabic",
        pronunciation: "A-zaa-zeel",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 89,
        english: "Saahir",
        arabic: "ساحر",
        urdu: "ساحر",
        persian: "ساحر",
        meaning: "Magician",
        origin: "Arabic",
        pronunciation: "Saa-hir",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 90,
        english: "Zafarullah",
        arabic: "ظفر الله",
        urdu: "ظفر اللہ",
        persian: "ظفر الله",
        meaning: "Boastful composition",
        origin: "Arabic",
        pronunciation: "Za-far ul-lah",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 91,
        english: "Sanam",
        arabic: "صنم",
        urdu: "صنم",
        persian: "صنم",
        meaning: "Idol",
        origin: "Arabic",
        pronunciation: "Sa-nam",
        gender: "both",
        status: "forbidden",
        quranic: false
    },
    {
        id: 92,
        english: "Ghulam Rasool",
        arabic: "غلام رسول",
        urdu: "غلام رسول",
        persian: "غلام رسول",
        meaning: "Slave of Prophet (same as Abdul Rasool)",
        origin: "Arabic/Urdu",
        pronunciation: "Ghu-laam Ra-sool",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 93,
        english: "Nafs",
        arabic: "نفس",
        urdu: "نفس",
        persian: "نفس",
        meaning: "Ego",
        origin: "Arabic",
        pronunciation: "Nafs",
        gender: "both",
        status: "forbidden",
        quranic: false
    },
    {
        id: 94,
        english: "Dajjal",
        arabic: "دجال",
        urdu: "دجال",
        persian: "دجال",
        meaning: "Antichrist",
        origin: "Arabic",
        pronunciation: "Daj-jaal",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 95,
        english: "Jadoo",
        arabic: "جادو",
        urdu: "جادو",
        persian: "جادو",
        meaning: "Magic",
        origin: "Arabic",
        pronunciation: "Jaa-doo",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 96,
        english: "Fana",
        arabic: "فناء",
        urdu: "فنا",
        persian: "فنا",
        meaning: "Destruction",
        origin: "Arabic",
        pronunciation: "Fa-naa",
        gender: "both",
        status: "forbidden",
        quranic: false
    },
    {
        id: 97,
        english: "Hadi Allah",
        arabic: "هادي الله",
        urdu: "ہادی اللہ",
        persian: "هادی الله",
        meaning: "Guide of Allah (theologically wrong)",
        origin: "Arabic",
        pronunciation: "Haa-di ul-lah",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 98,
        english: "Mushkil Kusha",
        arabic: "مشكل كشا",
        urdu: "مشکل کشا",
        persian: "مشکل کشا",
        meaning: "Problem solver (used for Ali, shirk risk)",
        origin: "Persian",
        pronunciation: "Mush-kil Ku-sha",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 99,
        english: "Zameer",
        arabic: "ضمير",
        urdu: "ضمیر",
        persian: "ضمیر",
        meaning: "Conscience (okay linguistically but weak spiritually)",
        origin: "Arabic",
        pronunciation: "Za-meer",
        gender: "boy",
        status: "forbidden",
        quranic: false
    },
    {
        id: 100,
        english: "Shah-e-Madina",
        arabic: "شاه المدينة",
        urdu: "شاہ مدینہ",
        persian: "شاه مدینه",
        meaning: "King of Madinah - exaggeration for Prophet ﷺ",
        origin: "Persian/Arabic",
        pronunciation: "Shah-e-Ma-di-na",
        gender: "boy",
        status: "forbidden",
        quranic: false
    }
];
