        // Names Database
        const namesDatabase = [
            {
                id: 1,
                english: "Muhammad",
                arabic: "محمد",
                urdu: "محمد",
                persian: "محمد",
                meaning: "Praised, Praiseworthy",
                origin: "Arabic",
                pronunciation: "Moo-ham-mad",
                gender: "boy",
                status: "allowed",
                quranic: true,
                ayah: "Surah Al-Imran 3:144"
            },
            {
                id: 2,
                english: "Aisha",
                arabic: "عائشة",
                urdu: "عائشہ",
                persian: "عایشه",
                meaning: "Living, Prosperous",
                origin: "Arabic",
                pronunciation: "Aa-ee-sha",
                gender: "girl",
                status: "allowed",
                quranic: false
            },
            {
                id: 3,
                english: "Ibrahim",
                arabic: "إبراهيم",
                urdu: "ابراہیم",
                persian: "ابراهیم",
                meaning: "Father of Many",
                origin: "Arabic",
                pronunciation: "Ib-raa-heem",
                gender: "boy",
                status: "allowed",
                quranic: true,
                ayah: "Surah Al-Baqarah 2:124"
            },
            {
                id: 4,
                english: "Fatima",
                arabic: "فاطمة",
                urdu: "فاطمہ",
                persian: "فاطمه",
                meaning: "Weaning, Abstaining",
                origin: "Arabic",
                pronunciation: "Faa-ti-ma",
                gender: "girl",
                status: "allowed",
                quranic: false
            },
            {
                id: 5,
                english: "Yusuf",
                arabic: "يوسف",
                urdu: "یوسف",
                persian: "یوسف",
                meaning: "God Will Increase",
                origin: "Arabic",
                pronunciation: "Yoo-soof",
                gender: "boy",
                status: "allowed",
                quranic: true,
                ayah: "Surah Yusuf 12:4"
            },
            {
                id: 6,
                english: "Zainab",
                arabic: "زينب",
                urdu: "زینب",
                persian: "زینب",
                meaning: "Fragrant Flower",
                origin: "Arabic",
                pronunciation: "Zay-nab",
                gender: "girl",
                status: "allowed",
                quranic: false
            },
            {
                id: 7,
                english: "Ali",
                arabic: "علي",
                urdu: "علی",
                persian: "علی",
                meaning: "Exalted, Noble",
                origin: "Arabic",
                pronunciation: "Aa-lee",
                gender: "boy",
                status: "allowed",
                quranic: false
            },
            {
                id: 8,
                english: "Maryam",
                arabic: "مريم",
                urdu: "مریم",
                persian: "مریم",
                meaning: "Beloved, Pure",
                origin: "Arabic",
                pronunciation: "Mar-yam",
                gender: "girl",
                status: "allowed",
                quranic: true,
                ayah: "Surah Maryam 19:16"
            },
            {
                id: 9,
                english: "Omar",
                arabic: "عمر",
                urdu: "عمر",
                persian: "عمر",
                meaning: "Long-Lived",
                origin: "Arabic",
                pronunciation: "O-mar",
                gender: "boy",
                status: "allowed",
                quranic: false
            },
            {
                id: 10,
                english: "Khadija",
                arabic: "خديجة",
                urdu: "خدیجہ",
                persian: "خدیجه",
                meaning: "Premature Child",
                origin: "Arabic",
                pronunciation: "Kha-dee-ja",
                gender: "girl",
                status: "allowed",
                quranic: false
            },
            {
                id: 11,
                english: "Musa",
                arabic: "موسى",
                urdu: "موسیٰ",
                persian: "موسی",
                meaning: "Drawn Out of Water",
                origin: "Arabic",
                pronunciation: "Moo-saa",
                gender: "boy",
                status: "allowed",
                quranic: true,
                ayah: "Surah Taha 20:9"
            },
            {
                id: 12,
                english: "Amina",
                arabic: "آمنة",
                urdu: "آمنہ",
                persian: "آمنه",
                meaning: "Trustworthy, Peaceful",
                origin: "Arabic",
                pronunciation: "Aa-mee-na",
                gender: "girl",
                status: "allowed",
                quranic: false
            },
            {
                id: 13,
                english: "Isa",
                arabic: "عيسى",
                urdu: "عیسیٰ",
                persian: "عیسی",
                meaning: "God is Salvation",
                origin: "Arabic",
                pronunciation: "Ee-saa",
                gender: "boy",
                status: "allowed",
                quranic: true,
                ayah: "Surah Al-Imran 3:45"
            },
            {
                id: 14,
                english: "Hafsa",
                arabic: "حفصة",
                urdu: "حفصہ",
                persian: "حفصه",
                meaning: "Young Lioness",
                origin: "Arabic",
                pronunciation: "Haf-sa",
                gender: "girl",
                status: "allowed",
                quranic: false
            },
            {
                id: 15,
                english: "Yunus",
                arabic: "يونس",
                urdu: "یونس",
                persian: "یونس",
                meaning: "Dove",
                origin: "Arabic",
                pronunciation: "Yoo-noos",
                gender: "boy",
                status: "allowed",
                quranic: true,
                ayah: "Surah Yunus 10:98"
            },
            {
                id: 16,
                english: "Safia",
                arabic: "صفية",
                urdu: "صفیہ",
                persian: "صفیه",
                meaning: "Pure, Best Friend",
                origin: "Arabic",
                pronunciation: "Sa-fee-ya",
                gender: "girl",
                status: "allowed",
                quranic: false
            },
            {
                id: 17,
                english: "Bilal",
                arabic: "بلال",
                urdu: "بلال",
                persian: "بلال",
                meaning: "Moistening, Refreshing",
                origin: "Arabic",
                pronunciation: "Bee-lal",
                gender: "boy",
                status: "allowed",
                quranic: false
            },
            {
                id: 18,
                english: "Asma",
                arabic: "أسماء",
                urdu: "اسماء",
                persian: "اسماء",
                meaning: "Supreme, Lofty",
                origin: "Arabic",
                pronunciation: "As-maa",
                gender: "girl",
                status: "allowed",
                quranic: false
            },
            {
                id: 19,
                english: "Zakariya",
                arabic: "زكريا",
                urdu: "زکریا",
                persian: "زکریا",
                meaning: "God Remembers",
                origin: "Arabic",
                pronunciation: "Za-ka-ree-ya",
                gender: "boy",
                status: "allowed",
                quranic: true,
                ayah: "Surah Maryam 19:2"
            },
            {
                id: 20,
                english: "Ruqayya",
                arabic: "رقية",
                urdu: "رقّیہ",
                persian: "رقیه",
                meaning: "Rising, Ascending",
                origin: "Arabic",
                pronunciation: "Roo-qay-ya",
                gender: "girl",
                status: "allowed",
                quranic: false
            },
            {
                id: 21,
                english: "Abdullah",
                arabic: "عبد الله",
                urdu: "عبداللہ",
                persian: "عبدالله",
                meaning: "Servant of God",
                origin: "Arabic",
                pronunciation: "Ab-dul-lah",
                gender: "boy",
                status: "allowed",
                quranic: false
            },
            {
                id: 22,
                english: "Sumayya",
                arabic: "سمية",
                urdu: "سمیہ",
                persian: "سمیه",
                meaning: "High Above, Elevated",
                origin: "Arabic",
                pronunciation: "Su-may-ya",
                gender: "girl",
                status: "allowed",
                quranic: false
            },
            {
                id: 23,
                english: "Hamza",
                arabic: "حمزة",
                urdu: "حمزہ",
                persian: "حمزه",
                meaning: "Lion, Strong",
                origin: "Arabic",
                pronunciation: "Ham-za",
                gender: "boy",
                status: "allowed",
                quranic: false
            },
            {
                id: 24,
                english: "Jameela",
                arabic: "جميلة",
                urdu: "جمیلہ",
                persian: "جمیله",
                meaning: "Beautiful",
                origin: "Arabic",
                pronunciation: "Ja-mee-la",
                gender: "girl",
                status: "allowed",
                quranic: false
            },
            // Forbidden names
            {
                id: 25,
                english: "Al-Ahad",
                arabic: "الأحد",
                urdu: "الاحد",
                persian: "الاحد",
                meaning: "The One (Name of Allah)",
                origin: "Arabic",
                pronunciation: "Al-Aa-had",
                gender: "boy",
                status: "forbidden",
                quranic: false
            },
            {
                id: 26,
                english: "Al-Khaliq",
                arabic: "الخالق",
                urdu: "الخالق",
                persian: "الخالق",
                meaning: "The Creator (Name of Allah)",
                origin: "Arabic",
                pronunciation: "Al-Khaa-liq",
                gender: "boy",
                status: "forbidden",
                quranic: false
            },
            {
                id: 27,
                english: "Malik al-Mulk",
                arabic: "مالك الملك",
                urdu: "مالک الملک",
                persian: "مالک الملک",
                meaning: "Owner of Sovereignty (Name of Allah)",
                origin: "Arabic",
                pronunciation: "Maa-lik al-Mulk",
                gender: "boy",
                status: "forbidden",
                quranic: false
            },
            {
                id: 28,
                english: "Ar-Rahman",
                arabic: "الرحمن",
                urdu: "الرحمن",
                persian: "الرحمن",
                meaning: "The Most Gracious (Name of Allah)",
                origin: "Arabic",
                pronunciation: "Ar-Rah-maan",
                gender: "boy",
                status: "forbidden",
                quranic: false
            },
            {
    id: 29,
    english: "Adam",
    arabic: "آدم",
    urdu: "آدم",
    persian: "آدم",
    meaning: "First Man, Earth",
    origin: "Arabic",
    pronunciation: "Aa-dam",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Al-Baqarah 2:31"
},
{
    id: 30,
    english: "Idris",
    arabic: "إدريس",
    urdu: "ادریس",
    persian: "ادریس",
    meaning: "Interpreter, Teacher",
    origin: "Arabic",
    pronunciation: "Id-rees",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Maryam 19:56"
},
{
    id: 31,
    english: "Hussain",
    arabic: "حسين",
    urdu: "حسین",
    persian: "حسین",
    meaning: "Handsome, Beautiful",
    origin: "Arabic",
    pronunciation: "Hus-sain",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 32,
    english: "Haroon",
    arabic: "هارون",
    urdu: "ہارون",
    persian: "هارون",
    meaning: "Messenger, Prophet",
    origin: "Arabic",
    pronunciation: "Haa-roon",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Maryam 19:53"
},
{
    id: 33,
    english: "Sulaiman",
    arabic: "سليمان",
    urdu: "سلیمان",
    persian: "سلیمان",
    meaning: "Man of Peace",
    origin: "Arabic",
    pronunciation: "Su-lai-maan",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Al-Baqarah 2:102"
},
{
    id: 34,
    english: "Dawud",
    arabic: "داود",
    urdu: "داؤد",
    persian: "داوود",
    meaning: "Beloved, Friend",
    origin: "Arabic",
    pronunciation: "Daa-wood",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Al-Baqarah 2:251"
},
{
    id: 35,
    english: "Yahya",
    arabic: "يحيى",
    urdu: "یحییٰ",
    persian: "یحیی",
    meaning: "God is Gracious",
    origin: "Arabic",
    pronunciation: "Yah-ya",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Maryam 19:7"
},
{
    id: 36,
    english: "Ismail",
    arabic: "إسماعيل",
    urdu: "اسماعیل",
    persian: "اسماعیل",
    meaning: "God Will Hear",
    origin: "Arabic",
    pronunciation: "Is-maa-eel",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Maryam 19:54"
},
{
    id: 37,
    english: "Yaqoob",
    arabic: "يعقوب",
    urdu: "یعقوب",
    persian: "یعقوب",
    meaning: "Supplanter, Holder of Heel",
    origin: "Arabic",
    pronunciation: "Yaa-qoob",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Al-Baqarah 2:132"
},
{
    id: 38,
    english: "Younis",
    arabic: "يونس",
    urdu: "یونس",
    persian: "یونس",
    meaning: "Dove",
    origin: "Arabic",
    pronunciation: "Yoo-nis",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Yunus 10:98"
},
{
    id: 39,
    english: "Luqman",
    arabic: "لقمان",
    urdu: "لقمان",
    persian: "لقمان",
    meaning: "Wise Man",
    origin: "Arabic",
    pronunciation: "Luq-maan",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Luqman 31:12"
},
{
    id: 40,
    english: "Hasan",
    arabic: "حسن",
    urdu: "حسن",
    persian: "حسن",
    meaning: "Handsome, Good",
    origin: "Arabic",
    pronunciation: "Ha-san",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 41,
    english: "Talha",
    arabic: "طلحة",
    urdu: "طلحہ",
    persian: "طلحه",
    meaning: "Fruitful Tree",
    origin: "Arabic",
    pronunciation: "Tal-ha",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 42,
    english: "Zubair",
    arabic: "زبیر",
    urdu: "زبیر",
    persian: "زبیر",
    meaning: "Strong, Powerful",
    origin: "Arabic",
    pronunciation: "Zoo-bair",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 43,
    english: "Saad",
    arabic: "سعد",
    urdu: "سعد",
    persian: "سعد",
    meaning: "Good Fortune, Lucky",
    origin: "Arabic",
    pronunciation: "Sa-ad",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 44,
    english: "Saeed",
    arabic: "سعید",
    urdu: "سعید",
    persian: "سعید",
    meaning: "Happy, Fortunate",
    origin: "Arabic",
    pronunciation: "Saa-eed",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 45,
    english: "Faris",
    arabic: "فارس",
    urdu: "فارس",
    persian: "فارس",
    meaning: "Knight, Horseman",
    origin: "Arabic",
    pronunciation: "Faa-ris",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 46,
    english: "Jafar",
    arabic: "جعفر",
    urdu: "جعفر",
    persian: "جعفر",
    meaning: "Stream, River",
    origin: "Arabic",
    pronunciation: "Jaa-far",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 47,
    english: "Khalid",
    arabic: "خالد",
    urdu: "خالد",
    persian: "خالد",
    meaning: "Eternal, Immortal",
    origin: "Arabic",
    pronunciation: "Khaa-lid",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 48,
    english: "Rashid",
    arabic: "رشید",
    urdu: "رشید",
    persian: "رشید",
    meaning: "Rightly Guided",
    origin: "Arabic",
    pronunciation: "Ra-sheed",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 49,
    english: "Tariq",
    arabic: "طارق",
    urdu: "طارق",
    persian: "طارق",
    meaning: "Morning Star, Knocker",
    origin: "Arabic",
    pronunciation: "Taa-riq",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah At-Tariq 86:1"
},
{
    id: 50,
    english: "Waleed",
    arabic: "ولید",
    urdu: "ولید",
    persian: "ولید",
    meaning: "Newborn Child",
    origin: "Arabic",
    pronunciation: "Waa-leed",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 51,
    english: "Sarah",
    arabic: "سارة",
    urdu: "سارہ",
    persian: "سارا",
    meaning: "Princess, Pure",
    origin: "Arabic",
    pronunciation: "Saa-rah",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 52,
    english: "Hajar",
    arabic: "هاجر",
    urdu: "ہاجر",
    persian: "هاجر",
    meaning: "Emigrant, One Who Migrates",
    origin: "Arabic",
    pronunciation: "Haa-jar",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 53,
    english: "Safiya",
    arabic: "صفیة",
    urdu: "صفیہ",
    persian: "صفیه",
    meaning: "Pure, Best Friend",
    origin: "Arabic",
    pronunciation: "Sa-fee-ya",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 54,
    english: "Layla",
    arabic: "لیلى",
    urdu: "لیلیٰ",
    persian: "لیلا",
    meaning: "Night, Dark Beauty",
    origin: "Arabic",
    pronunciation: "Lai-la",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 55,
    english: "Noor",
    arabic: "نور",
    urdu: "نور",
    persian: "نور",
    meaning: "Light, Illumination",
    origin: "Arabic",
    pronunciation: "Noor",
    gender: "girl",
    status: "allowed",
    quranic: true,
    ayah: "Surah An-Nur 24:35"
},
{
    id: 56,
    english: "Hooriya",
    arabic: "حورية",
    urdu: "حوریہ",
    persian: "حوریه",
    meaning: "Angel of Paradise",
    origin: "Arabic",
    pronunciation: "Hoo-ri-ya",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 57,
    english: "Jannat",
    arabic: "جنة",
    urdu: "جنت",
    persian: "جنت",
    meaning: "Paradise, Garden",
    origin: "Arabic",
    pronunciation: "Jan-nat",
    gender: "girl",
    status: "allowed",
    quranic: true,
    ayah: "Surah Al-Baqarah 2:25"
},
{
    id: 58,
    english: "Ayesha",
    arabic: "عائشة",
    urdu: "عائشہ",
    persian: "عایشه",
    meaning: "Living, Prosperous",
    origin: "Arabic",
    pronunciation: "Aa-ye-sha",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 59,
    english: "Rabia",
    arabic: "رابعة",
    urdu: "رابعہ",
    persian: "رابعه",
    meaning: "Fourth, Spring",
    origin: "Arabic",
    pronunciation: "Ra-bia",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 60,
    english: "Zara",
    arabic: "زارا",
    urdu: "زارا",
    persian: "زارا",
    meaning: "Princess, Flower",
    origin: "Arabic",
    pronunciation: "Zaa-ra",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 61,
    english: "Yasmin",
    arabic: "ياسمين",
    urdu: "یاسمین",
    persian: "یاسمین",
    meaning: "Jasmine Flower",
    origin: "Arabic",
    pronunciation: "Yas-min",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 62,
    english: "Nadia",
    arabic: "نادية",
    urdu: "نادیہ",
    persian: "نادیه",
    meaning: "Caller, Announcer",
    origin: "Arabic",
    pronunciation: "Naa-dia",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 63,
    english: "Samira",
    arabic: "سميرة",
    urdu: "سمیرہ",
    persian: "سمیرا",
    meaning: "Entertaining Companion",
    origin: "Arabic",
    pronunciation: "Sa-mee-ra",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 64,
    english: "Farida",
    arabic: "فريدة",
    urdu: "فریدہ",
    persian: "فریده",
    meaning: "Unique, Precious",
    origin: "Arabic",
    pronunciation: "Fa-ree-da",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 65,
    english: "Habiba",
    arabic: "حبيبة",
    urdu: "حبیبہ",
    persian: "حبیبه",
    meaning: "Beloved, Darling",
    origin: "Arabic",
    pronunciation: "Ha-bee-ba",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 66,
    english: "Karima",
    arabic: "كريمة",
    urdu: "کریمہ",
    persian: "کریمه",
    meaning: "Generous, Noble",
    origin: "Arabic",
    pronunciation: "Ka-ree-ma",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 67,
    english: "Latifa",
    arabic: "لطيفة",
    urdu: "لطیفہ",
    persian: "لطیفه",
    meaning: "Gentle, Kind",
    origin: "Arabic",
    pronunciation: "La-tee-fa",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 68,
    english: "Mariam",
    arabic: "مريم",
    urdu: "مریم",
    persian: "مریم",
    meaning: "Beloved, Pure",
    origin: "Arabic",
    pronunciation: "Ma-ri-am",
    gender: "girl",
    status: "allowed",
    quranic: true,
    ayah: "Surah Maryam 19:16"
},
{
    id: 69,
    english: "Naima",
    arabic: "نعيمة",
    urdu: "نعیمہ",
    persian: "نعیمه",
    meaning: "Tranquil, Peaceful",
    origin: "Arabic",
    pronunciation: "Naa-ee-ma",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 70,
    english: "Rukhsar",
    arabic: "روخسار",
    urdu: "رخسار",
    persian: "رخسار",
    meaning: "Cheek, Beautiful Face",
    origin: "Persian",
    pronunciation: "Rukh-saar",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 71,
    english: "Basil",
    arabic: "باسل",
    urdu: "باسل",
    persian: "باسل",
    meaning: "Brave, Valiant",
    origin: "Arabic",
    pronunciation: "Ba-sil",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 72,
    english: "Dania",
    arabic: "دانیا",
    urdu: "دانیا",
    persian: "دانیا",
    meaning: "Close, Near; Wise Woman",
    origin: "Arabic",
    pronunciation: "Da-ni-ya",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 73,
    english: "Farhan",
    arabic: "فرحان",
    urdu: "فرحان",
    persian: "فرحان",
    meaning: "Happy, Joyful",
    origin: "Arabic",
    pronunciation: "Far-han",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 74,
    english: "Gulzar",
    arabic: "گلزار",
    urdu: "گلزار",
    persian: "گلزار",
    meaning: "Garden of Flowers, Blossoming",
    origin: "Persian",
    pronunciation: "Gul-zar",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 75,
    english: "Hadiya",
    arabic: "هادية",
    urdu: "ہادیہ",
    persian: "هادیه",
    meaning: "Guidance; Gifted, Guided",
    origin: "Arabic",
    pronunciation: "Ha-di-ya",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 76,
    english: "Ibtisam",
    arabic: "ابتسام",
    urdu: "ابتسام",
    persian: "ابتسام",
    meaning: "Smile, Cheerful Face",
    origin: "Arabic",
    pronunciation: "Ib-ti-sam",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 77,
    english: "Jawad",
    arabic: "جواد",
    urdu: "جواد",
    persian: "جواد",
    meaning: "Generous, Noble",
    origin: "Arabic",
    pronunciation: "Ja-wad",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 78,
    english: "Kainat",
    arabic: "کائنات",
    urdu: "کائنات",
    persian: "کائنات",
    meaning: "Universe, Creation",
    origin: "Urdu",
    pronunciation: "Kai-nat",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 79,
    english: "Mahnoor",
    arabic: "ماہ نور",
    urdu: "ماہ نور",
    persian: "ماه نور",
    meaning: "Moonlight, Radiant Face",
    origin: "Persian",
    pronunciation: "Mah-noor",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 80,
    english: "Naveed",
    arabic: "نوید",
    urdu: "نوید",
    persian: "نوید",
    meaning: "Good News, Glad Tidings",
    origin: "Persian",
    pronunciation: "Na-veed",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 81,
    english: "Omair",
    arabic: "عمير",
    urdu: "عمیر",
    persian: "عمیر",
    meaning: "Long-Lived, Intelligent",
    origin: "Arabic",
    pronunciation: "O-mair",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 82,
    english: "Pari",
    arabic: "پری",
    urdu: "پری",
    persian: "پری",
    meaning: "Fairy, Beautiful Being",
    origin: "Persian",
    pronunciation: "Pa-ri",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 83,
    english: "Qamar",
    arabic: "قمر",
    urdu: "قمر",
    persian: "قمر",
    meaning: "Moon, Radiant",
    origin: "Arabic",
    pronunciation: "Qa-mar",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 84,
    english: "Rameen",
    arabic: "رامین",
    urdu: "رامین",
    persian: "رامین",
    meaning: "Sunny, Joyful; Pleasant",
    origin: "Persian",
    pronunciation: "Ra-meen",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 85,
    english: "Saima",
    arabic: "صائمہ",
    urdu: "صائمہ",
    persian: "صائمه",
    meaning: "One who Fasts; Devout",
    origin: "Arabic",
    pronunciation: "Sai-ma",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 86,
    english: "Tahir",
    arabic: "طاہر",
    urdu: "طاہر",
    persian: "طاهر",
    meaning: "Pure, Chaste",
    origin: "Arabic",
    pronunciation: "Ta-hir",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 87,
    english: "Urooj",
    arabic: "عروج",
    urdu: "عروج",
    persian: "عروج",
    meaning: "Ascent, Rise, Elevation",
    origin: "Arabic",
    pronunciation: "U-rooj",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 88,
    english: "Yumna",
    arabic: "یمنہ",
    urdu: "یمنہ",
    persian: "یمنه",
    meaning: "Blessed, Auspicious",
    origin: "Arabic",
    pronunciation: "Yum-na",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 89,
    english: "Zahir",
    arabic: "ظاہر",
    urdu: "ظاہر",
    persian: "ظاهر",
    meaning: "Visible, Manifest; Brilliant",
    origin: "Arabic",
    pronunciation: "Za-hir",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 90,
    english: "Basma",
    arabic: "بسمة",
    urdu: "بسمة",
    persian: "بسمة",
    meaning: "Smile, Cheerful Countenance",
    origin: "Arabic",
    pronunciation: "Bas-ma",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 91,
    english: "Eimaan",
    arabic: "ایمان",
    urdu: "ایمان",
    persian: "ایمان",
    meaning: "Faith, Belief; Sincere Trust",
    origin: "Arabic",
    pronunciation: "Ei-maan",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 92,
    english: "Fawad",
    arabic: "فؤاد",
    urdu: "فواد",
    persian: "فواد",
    meaning: "Heart, Courageous Heart",
    origin: "Arabic",
    pronunciation: "Fa-wad",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 93,
    english: "Ghazanfar",
    arabic: "غضنفر",
    urdu: "غزنفر",
    persian: "غزنفر",
    meaning: "Lion, Brave Warrior",
    origin: "Persian",
    pronunciation: "Gha-zan-far",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 94,
    english: "Huma",
    arabic: "ہما",
    urdu: "ہما",
    persian: "هما",
    meaning: "Mythic Bird; Lucky, Benevolent",
    origin: "Persian",
    pronunciation: "Hu-ma",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 95,
    english: "Iklil",
    arabic: "إكلیل",
    urdu: "اکلیل",
    persian: "اکلیل",
    meaning: "Crown, Garland",
    origin: "Arabic",
    pronunciation: "Ik-lil",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 96,
    english: "Jumana",
    arabic: "جمانہ",
    urdu: "جمانہ",
    persian: "جمانه",
    meaning: "Silver Pearl, Precious",
    origin: "Arabic",
    pronunciation: "Ju-ma-na",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 97,
    english: "Kashan",
    arabic: "کاشان",
    urdu: "کاشان",
    persian: "کاشان",
    meaning: "From the City of Kashan; Beautiful Place",
    origin: "Persian",
    pronunciation: "Ka-shan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 98,
    english: "Labeeb",
    arabic: "لبيب",
    urdu: "ل بیب",
    persian: "لبيب",
    meaning: "Sensible, Intelligent, Wise",
    origin: "Arabic",
    pronunciation: "La-beeb",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 99,
    english: "Mazin",
    arabic: "مزن",
    urdu: "مازن",
    persian: "مازن",
    meaning: "Proper Name; Strong and Glorious",
    origin: "Arabic",
    pronunciation: "Ma-zin",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 100,
    english: "Nayla",
    arabic: "نائلہ",
    urdu: "نایلہ",
    persian: "نایلا",
    meaning: "Attainer, Successful One",
    origin: "Arabic",
    pronunciation: "Nay-la",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 101,
    english: "Omaima",
    arabic: "امیمہ",
    urdu: "امیمہ",
    persian: "امیمه",
    meaning: "Little Mother; Gentle Care",
    origin: "Arabic",
    pronunciation: "O-mai-ma",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 102,
    english: "Parisa",
    arabic: "پاریسا",
    urdu: "پاریسا",
    persian: "پاریسا",
    meaning: "Like a Fairy, Elegant",
    origin: "Persian",
    pronunciation: "Pa-ri-sa",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 103,
    english: "Qudamah",
    arabic: "قدامة",
    urdu: "قدامہ",
    persian: "قدامه",
    meaning: "Bravery, Courageous",
    origin: "Arabic",
    pronunciation: "Qu-da-mah",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 104,
    english: "Rafi",
    arabic: "رفیع",
    urdu: "رفیع",
    persian: "رفیع",
    meaning: "Exalted, High, Noble",
    origin: "Arabic",
    pronunciation: "Ra-fi",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 105,
    english: "Salsabil",
    arabic: "سلسبیل",
    urdu: "سلسبیل",
    persian: "سلسبیل",
    meaning: "A Spring in Paradise, Pure Water",
    origin: "Arabic",
    pronunciation: "Sal-sa-bil",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 106,
    english: "Tahira",
    arabic: "طاهرة",
    urdu: "طاہرہ",
    persian: "طاهره",
    meaning: "Pure, Chaste, Virtuous",
    origin: "Arabic",
    pronunciation: "Ta-hi-ra",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 107,
    english: "Uzair",
    arabic: "عزیر",
    urdu: "عزیر",
    persian: "عزیر",
    meaning: "Helper; Mighty One (Ezra)",
    origin: "Arabic",
    pronunciation: "U-zair",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 108,
    english: "Widad",
    arabic: "وداد",
    urdu: "وداد",
    persian: "وداد",
    meaning: "Love, Affection, Friendship",
    origin: "Arabic",
    pronunciation: "Wi-dad",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 109,
    english: "Yara",
    arabic: "یارا",
    urdu: "یارا",
    persian: "یارا",
    meaning: "Beloved, Small Butterfly",
    origin: "Persian",
    pronunciation: "Ya-ra",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 110,
    english: "Zarmeen",
    arabic: "زرمین",
    urdu: "زرمین",
    persian: "زرمین",
    meaning: "Golden Land, Golden One",
    origin: "Persian",
    pronunciation: "Zar-meen",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 111,
    english: "Arham",
    arabic: "أرحم",
    urdu: "ارحم",
    persian: "ارحم",
    meaning: "Most Merciful, Compassionate",
    origin: "Arabic",
    pronunciation: "Ar-ham",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 112,
    english: "Zunaira",
    arabic: "زنيّرة",
    urdu: "زنینہ",
    persian: "زنینه",
    meaning: "Guiding Light, Radiant",
    origin: "Arabic",
    pronunciation: "Zu-nai-ra",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 113,
    english: "Rayyan",
    arabic: "ريّان",
    urdu: "ریان",
    persian: "ریان",
    meaning: "Gate of Paradise for Fasting People",
    origin: "Arabic",
    pronunciation: "Ray-yan",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Sahih Muslim 1152"
},
{
    id: 114,
    english: "Abrar",
    arabic: "أبرار",
    urdu: "ابرار",
    persian: "ابرار",
    meaning: "Pious, Righteous",
    origin: "Arabic",
    pronunciation: "Ab-rar",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Al-Insan 76:5"
},
{
    id: 115,
    english: "Nawal",
    arabic: "نوال",
    urdu: "نوال",
    persian: "نوال",
    meaning: "Gift, Blessing",
    origin: "Arabic",
    pronunciation: "Na-wal",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 116,
    english: "Firdaus",
    arabic: "فردوس",
    urdu: "فردوس",
    persian: "فردوس",
    meaning: "Highest Garden in Paradise",
    origin: "Arabic",
    pronunciation: "Fir-daus",
    gender: "girl",
    status: "allowed",
    quranic: true,
    ayah: "Surah Al-Kahf 18:107"
},
{
    id: 117,
    english: "Azlan",
    arabic: "أزلان",
    urdu: "ازلان",
    persian: "ازلان",
    meaning: "Lion, Brave",
    origin: "Arabic",
    pronunciation: "Az-lan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 118,
    english: "Yasira",
    arabic: "يسيرة",
    urdu: "یسیرہ",
    persian: "یسیره",
    meaning: "Easy, Comfortable",
    origin: "Arabic",
    pronunciation: "Ya-si-ra",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 119,
    english: "Mubeen",
    arabic: "مبين",
    urdu: "مبین",
    persian: "مبین",
    meaning: "Clear, Manifest",
    origin: "Arabic",
    pronunciation: "Mu-been",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah An-Nur 24:1"
},
{
    id: 120,
    english: "Alina",
    arabic: "ألينا",
    urdu: "آلینا",
    persian: "آلینا",
    meaning: "Noble, Beautiful",
    origin: "Arabic",
    pronunciation: "A-li-na",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 121,
    english: "Shahid",
    arabic: "شهيد",
    urdu: "شہید",
    persian: "شهید",
    meaning: "Witness, Martyr",
    origin: "Arabic",
    pronunciation: "Sha-hid",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Al-Baqarah 2:143"
},
{
    id: 122,
    english: "Nashit",
    arabic: "نشيط",
    urdu: "نشیط",
    persian: "نشیط",
    meaning: "Active, Energetic",
    origin: "Arabic",
    pronunciation: "Na-shit",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 123,
    english: "Alvira",
    arabic: "الفيرة",
    urdu: "الویرا",
    persian: "الویرا",
    meaning: "Truthful, Princess",
    origin: "Arabic",
    pronunciation: "Al-vi-ra",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 124,
    english: "Waseem",
    arabic: "وسيم",
    urdu: "وسیم",
    persian: "وسیم",
    meaning: "Handsome, Graceful",
    origin: "Arabic",
    pronunciation: "Wa-seem",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 125,
    english: "Zimal",
    arabic: "زمل",
    urdu: "زمل",
    persian: "زمل",
    meaning: "Garment, Covering",
    origin: "Arabic",
    pronunciation: "Zi-mal",
    gender: "girl",
    status: "allowed",
    quranic: true,
    ayah: "Surah Al-A'raf 7:26"
},
{
    id: 126,
    english: "Arsalan",
    arabic: "أرسلان",
    urdu: "ارسلان",
    persian: "ارسلان",
    meaning: "Lion, Brave",
    origin: "Persian",
    pronunciation: "Ar-sa-lan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 127,
    english: "Nimra",
    arabic: "نمرة",
    urdu: "نمرہ",
    persian: "نمره",
    meaning: "Princess, Pure",
    origin: "Arabic",
    pronunciation: "Nim-ra",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 128,
    english: "Danish",
    arabic: "دانش",
    urdu: "دانش",
    persian: "دانش",
    meaning: "Knowledge, Wisdom",
    origin: "Persian",
    pronunciation: "Da-nish",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 129,
    english: "Aizal",
    arabic: "أيزل",
    urdu: "ایزل",
    persian: "ایزل",
    meaning: "Precious, Valuable",
    origin: "Arabic",
    pronunciation: "Ai-zal",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 130,
    english: "Zoha",
    arabic: "زہى",
    urdu: "زوہا",
    persian: "زوها",
    meaning: "Light, Dawn",
    origin: "Arabic",
    pronunciation: "Zo-ha",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 131,
    english: "Amaan",
    arabic: "أمان",
    urdu: "امان",
    persian: "امان",
    meaning: "Peace, Safety",
    origin: "Arabic",
    pronunciation: "A-maan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 132,
    english: "Inaya",
    arabic: "عناية",
    urdu: "عنایہ",
    persian: "عنایه",
    meaning: "Care, Concern",
    origin: "Arabic",
    pronunciation: "I-na-ya",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 133,
    english: "Shayan",
    arabic: "شايان",
    urdu: "شایان",
    persian: "شایان",
    meaning: "Worthy, Deserving",
    origin: "Persian",
    pronunciation: "Sha-yan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 134,
    english: "Zaraq",
    arabic: "زراق",
    urdu: "زراق",
    persian: "زراق",
    meaning: "Shining, Bright",
    origin: "Arabic",
    pronunciation: "Za-raq",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 135,
    english: "Alizay",
    arabic: "عليزي",
    urdu: "علیزے",
    persian: "علیزای",
    meaning: "Princess, Noble",
    origin: "Arabic",
    pronunciation: "A-li-zay",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 136,
    english: "Rohan",
    arabic: "روهان",
    urdu: "روحان",
    persian: "روحان",
    meaning: "Soul, Spiritual",
    origin: "Persian",
    pronunciation: "Ro-han",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 137,
    english: "Anaya",
    arabic: "عنایا",
    urdu: "عنایا",
    persian: "عنایا",
    meaning: "God's Answer, Caring",
    origin: "Arabic",
    pronunciation: "A-na-ya",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 138,
    english: "Zavian",
    arabic: "زافيان",
    urdu: "زافیان",
    persian: "زافیان",
    meaning: "Bright, Shining",
    origin: "Arabic",
    pronunciation: "Za-vi-an",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 139,
    english: "Eshan",
    arabic: "عشان",
    urdu: "عشان",
    persian: "عشان",
    meaning: "Desire, Wish",
    origin: "Persian",
    pronunciation: "E-shan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 140,
    english: "Zaraab",
    arabic: "زراب",
    urdu: "زراب",
    persian: "زراب",
    meaning: "Shining, Brilliant",
    origin: "Arabic",
    pronunciation: "Za-raab",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 141,
    english: "Al-Malik",
    arabic: "الملك",
    urdu: "الملک",
    persian: "الملک",
    meaning: "The King (Name of Allah)",
    origin: "Arabic",
    pronunciation: "Al-Ma-lik",
    gender: "boy",
    status: "forbidden",
    quranic: false,
},
{
    id: 142,
    english: "Ar-Razzaq",
    arabic: "الرزاق",
    urdu: "الرزاق",
    persian: "الرزاق",
    meaning: "The Provider (Name of Allah)",
    origin: "Arabic",
    pronunciation: "Ar-Raz-zaq",
    gender: "boy",
    status: "forbidden",
    quranic: false,
},
{
    id: 143,
    english: "Al-Muhaimin",
    arabic: "المهيمن",
    urdu: "المهیمن",
    persian: "المهیمن",
    meaning: "The Protector (Name of Allah)",
    origin: "Arabic",
    pronunciation: "Al-Mu-hai-min",
    gender: "boy",
    status: "forbidden",
    quranic: false,
},
{
    id: 144,
    english: "Al-Jabbar",
    arabic: "الجبار",
    urdu: "الجبار",
    persian: "الجبار",
    meaning: "The Compeller (Name of Allah)",
    origin: "Arabic",
    pronunciation: "Al-Jab-bar",
    gender: "boy",
    status: "forbidden",
    quranic: false,
},
{
    id: 145,
    english: "Al-Mutakabbir",
    arabic: "المتكبر",
    urdu: "المتکبر",
    persian: "المتکبر",
    meaning: "The Supreme (Name of Allah)",
    origin: "Arabic",
    pronunciation: "Al-Mu-ta-kab-bir",
    gender: "boy",
    status: "forbidden",
    quranic: false,
},
{
    id: 146,
    english: "Nuh",
    arabic: "نوح",
    urdu: "نوح",
    persian: "نوح",
    meaning: "Prophet Noah",
    origin: "Arabic",
    pronunciation: "Nooh",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Nuh 71:1"
},
{
    id: 147,
    english: "Hud",
    arabic: "هود",
    urdu: "ہود",
    persian: "هود",
    meaning: "Prophet Hud",
    origin: "Arabic",
    pronunciation: "Hood",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Hud 11:50"
},
{
    id: 148,
    english: "Salih",
    arabic: "صالح",
    urdu: "صالح",
    persian: "صالح",
    meaning: "Prophet Salih",
    origin: "Arabic",
    pronunciation: "Sa-lih",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Ash-Shu'ara 26:142"
},
{
    id: 149,
    english: "Shuaib",
    arabic: "شعيب",
    urdu: "شعیب",
    persian: "شعیب",
    meaning: "Prophet Shuaib",
    origin: "Arabic",
    pronunciation: "Shu-aib",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Al-A'raf 7:85"
},
{
    id: 150,
    english: "Ayyub",
    arabic: "أيوب",
    urdu: "ایوب",
    persian: "ایوب",
    meaning: "Prophet Job",
    origin: "Arabic",
    pronunciation: "Ay-yoob",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah An-Nisa 4:163"
},
{
    id: 151,
    english: "Zorain",
    arabic: "زورين",
    urdu: "زورین",
    persian: "زورین",
    meaning: "Beautiful Flower, Shining Star",
    origin: "Arabic",
    pronunciation: "Zo-rain",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 152,
    english: "Alishba",
    arabic: "عليشبا",
    urdu: "علیشبا",
    persian: "علیشبا",
    meaning: "Beautiful, Pretty",
    origin: "Arabic",
    pronunciation: "A-lish-ba",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 153,
    english: "Ayat",
    arabic: "آيات",
    urdu: "آیات",
    persian: "آیات",
    meaning: "Signs of God, Quranic Verses",
    origin: "Arabic",
    pronunciation: "A-yat",
    gender: "girl",
    status: "allowed",
    quranic: true,
    ayah: "Surah Fussilat 41:53"
},
{
    id: 154,
    english: "Barakah",
    arabic: "بركة",
    urdu: "برکت",
    persian: "برکت",
    meaning: "Blessing, Abundance",
    origin: "Arabic",
    pronunciation: "Ba-ra-kah",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Al-A'raf 7:96"
},
{
    id: 155,
    english: "Daniyal",
    arabic: "دانيال",
    urdu: "دانیال",
    persian: "دانیال",
    meaning: "God is My Judge",
    origin: "Arabic",
    pronunciation: "Da-ni-yal",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 156,
    english: "Eiraj",
    arabic: "إيراج",
    urdu: "ایراج",
    persian: "ایراج",
    meaning: "Splendor, Radiance",
    origin: "Persian",
    pronunciation: "Ei-raj",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 157,
    english: "Fajar",
    arabic: "فجر",
    urdu: "فجر",
    persian: "فجر",
    meaning: "Dawn, Morning",
    origin: "Arabic",
    pronunciation: "Fa-jar",
    gender: "girl",
    status: "allowed",
    quranic: true,
    ayah: "Surah Al-Fajr 89:1"
},
{
    id: 158,
    english: "Gulshan",
    arabic: "گلشن",
    urdu: "گلشن",
    persian: "گلشن",
    meaning: "Rose Garden, Flower Garden",
    origin: "Persian",
    pronunciation: "Gul-shan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 159,
    english: "Hadi",
    arabic: "هادي",
    urdu: "ہادی",
    persian: "هادی",
    meaning: "Guide, Leader",
    origin: "Arabic",
    pronunciation: "Ha-di",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Al-Furqan 25:31"
},
{
    id: 160,
    english: "Iman",
    arabic: "إيمان",
    urdu: "ایمان",
    persian: "ایمان",
    meaning: "Faith, Belief",
    origin: "Arabic",
    pronunciation: "I-man",
    gender: "girl",
    status: "allowed",
    quranic: true,
    ayah: "Surah Al-Hujurat 49:7"
},
{
    id: 161,
    english: "Jannah",
    arabic: "جنة",
    urdu: "جنت",
    persian: "جنت",
    meaning: "Paradise, Garden",
    origin: "Arabic",
    pronunciation: "Jan-nah",
    gender: "girl",
    status: "allowed",
    quranic: true,
    ayah: "Surah Al-Baqarah 2:25"
},
{
    id: 162,
    english: "Kawthar",
    arabic: "كوثر",
    urdu: "کوثر",
    persian: "کوثر",
    meaning: "Abundance, River in Paradise",
    origin: "Arabic",
    pronunciation: "Kaw-thar",
    gender: "girl",
    status: "allowed",
    quranic: true,
    ayah: "Surah Al-Kawthar 108:1"
},
{
    id: 163,
    english: "Lut",
    arabic: "لوط",
    urdu: "لوط",
    persian: "لوط",
    meaning: "Prophet Lot",
    origin: "Arabic",
    pronunciation: "Loot",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Ash-Shu'ara 26:160"
},
{
    id: 164,
    english: "Mariyah",
    arabic: "مارية",
    urdu: "ماریہ",
    persian: "ماریه",
    meaning: "Pure, Pious",
    origin: "Arabic",
    pronunciation: "Ma-ri-yah",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 165,
    english: "Nuhayr",
    arabic: "نهير",
    urdu: "نہیر",
    persian: "نهیر",
    meaning: "River, Stream",
    origin: "Arabic",
    pronunciation: "Nu-hayr",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 166,
    english: "Omarah",
    arabic: "عمارة",
    urdu: "عمارہ",
    persian: "عماره",
    meaning: "Long Life, Prosperity",
    origin: "Arabic",
    pronunciation: "O-ma-rah",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 167,
    english: "Pakeeza",
    arabic: "باكيزة",
    urdu: "پاکیزہ",
    persian: "پاکیزه",
    meaning: "Pure, Clean",
    origin: "Persian",
    pronunciation: "Pa-kee-za",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 168,
    english: "Qasim",
    arabic: "قاسم",
    urdu: "قاسم",
    persian: "قاسم",
    meaning: "Divider, Distributor",
    origin: "Arabic",
    pronunciation: "Qa-sim",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 169,
    english: "Rahma",
    arabic: "رحمة",
    urdu: "رحمت",
    persian: "رحمت",
    meaning: "Mercy, Compassion",
    origin: "Arabic",
    pronunciation: "Rah-ma",
    gender: "girl",
    status: "allowed",
    quranic: true,
    ayah: "Surah Al-An'am 6:12"
},
{
    id: 170,
    english: "Saba",
    arabic: "سبأ",
    urdu: "سبا",
    persian: "سبا",
    meaning: "Sheba, Morning Breeze",
    origin: "Arabic",
    pronunciation: "Sa-ba",
    gender: "girl",
    status: "allowed",
    quranic: true,
    ayah: "Surah Saba 34:15"
},
{
    id: 171,
    english: "Tasneem",
    arabic: "تسنيم",
    urdu: "تسنیم",
    persian: "تسنیم",
    meaning: "Fountain in Paradise",
    origin: "Arabic",
    pronunciation: "Tas-neem",
    gender: "girl",
    status: "allowed",
    quranic: true,
    ayah: "Surah Al-Mutaffifin 83:27"
},
{
    id: 172,
    english: "Ubaid",
    arabic: "عبيد",
    urdu: "عبید",
    persian: "عبید",
    meaning: "Little Servant",
    origin: "Arabic",
    pronunciation: "U-baid",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 173,
    english: "Wafa",
    arabic: "وفاء",
    urdu: "وفا",
    persian: "وفا",
    meaning: "Loyalty, Faithfulness",
    origin: "Arabic",
    pronunciation: "Wa-fa",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 174,
    english: "Xavier",
    arabic: "زافير",
    urdu: "زیویر",
    persian: "زاویر",
    meaning: "Bright, Splendid",
    origin: "Arabic",
    pronunciation: "Za-veer",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 175,
    english: "Yasir",
    arabic: "ياسر",
    urdu: "یاسر",
    persian: "یاسر",
    meaning: "Wealthy, Prosperous",
    origin: "Arabic",
    pronunciation: "Ya-sir",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 176,
    english: "Zikra",
    arabic: "ذكرى",
    urdu: "ذکرا",
    persian: "ذکرا",
    meaning: "Memory, Remembrance",
    origin: "Arabic",
    pronunciation: "Zik-ra",
    gender: "girl",
    status: "allowed",
    quranic: true,
    ayah: "Surah Al-Muddathir 74:49"
},
{
    id: 177,
    english: "Arif",
    arabic: "عارف",
    urdu: "عارف",
    persian: "عارف",
    meaning: "Knowledgeable, Wise",
    origin: "Arabic",
    pronunciation: "A-rif",
    gender: "boy",
    status: "allowed",
    ayah: false
},
{
    id: 178,
    english: "Bushra",
    arabic: "بشرى",
    urdu: "بشریٰ",
    persian: "بشری",
    meaning: "Good News, Glad Tidings",
    origin: "Arabic",
    pronunciation: "Bush-ra",
    gender: "girl",
    status: "allowed",
    quranic: true,
    ayah: "Surah Yunus 10:64"
},
{
    id: 179,
    english: "Chandni",
    arabic: "شاندني",
    urdu: "چاندنی",
    persian: "چاندنی",
    meaning: "Moonlight",
    origin: "Urdu",
    pronunciation: "Chand-ni",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 180,
    english: "Dilawar",
    arabic: "دلاور",
    urdu: "دلاور",
    persian: "دلاور",
    meaning: "Brave, Courageous",
    origin: "Persian",
    pronunciation: "Di-la-war",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 181,
    english: "Ehsan",
    arabic: "إحسان",
    urdu: "احسان",
    persian: "احسان",
    meaning: "Benevolence, Charity",
    origin: "Arabic",
    pronunciation: "Eh-san",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah An-Nahl 16:90"
},
{
    id: 182,
    english: "Fahad",
    arabic: "فهيد",
    urdu: "فہد",
    persian: "فهد",
    meaning: "Lion, Panther",
    origin: "Arabic",
    pronunciation: "Fa-had",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 183,
    english: "Gohar",
    arabic: "جوهر",
    urdu: "گوہر",
    persian: "گوهر",
    meaning: "Pearl, Jewel",
    origin: "Persian",
    pronunciation: "Go-har",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 184,
    english: "Hira",
    arabic: "حراء",
    urdu: "حرا",
    persian: "حرا",
    meaning: "Diamond, Precious Stone",
    origin: "Arabic",
    pronunciation: "Hi-ra",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 185,
    english: "Iqbal",
    arabic: "إقبال",
    urdu: "اقبال",
    persian: "اقبال",
    meaning: "Prosperity, Good Fortune",
    origin: "Arabic",
    pronunciation: "Iq-bal",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 186,
    english: "Jalal",
    arabic: "جلال",
    urdu: "جلال",
    persian: "جلال",
    meaning: "Glory, Majesty",
    origin: "Arabic",
    pronunciation: "Ja-lal",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 187,
    english: "Kashif",
    arabic: "كاشف",
    urdu: "کاشف",
    persian: "کاشف",
    meaning: "Revealer, Discoverer",
    origin: "Arabic",
    pronunciation: "Ka-shif",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 188,
    english: "Lubna",
    arabic: "لبنى",
    urdu: "لبنیٰ",
    persian: "لبنی",
    meaning: "Storax Tree, Sweetness",
    origin: "Arabic",
    pronunciation: "Lub-na",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 189,
    english: "Mujtaba",
    arabic: "مجتبى",
    urdu: "مجتبیٰ",
    persian: "مجتبی",
    meaning: "Chosen, Selected",
    origin: "Arabic",
    pronunciation: "Muj-ta-ba",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 190,
    english: "Naseem",
    arabic: "نسيم",
    urdu: "نسیم",
    persian: "نسیم",
    meaning: "Breeze, Fresh Air",
    origin: "Arabic",
    pronunciation: "Na-seem",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 191,
    english: "Al-Quddus",
    arabic: "القدوس",
    urdu: "القدوس",
    persian: "القدوس",
    meaning: "The Holy (Name of Allah)",
    origin: "Arabic",
    pronunciation: "Al-Qud-doos",
    gender: "boy",
    status: "forbidden",
    quranic: false,
},
{
    id: 192,
    english: "As-Salam",
    arabic: "السلام",
    urdu: "السلام",
    persian: "السلام",
    meaning: "The Source of Peace (Name of Allah)",
    origin: "Arabic",
    pronunciation: "As-Sa-laam",
    gender: "boy",
    status: "forbidden",
    quranic: false,
},
{
    id: 193,
    english: "Al-Mu'min",
    arabic: "المؤمن",
    urdu: "المؤمن",
    persian: "المؤمن",
    meaning: "The Guardian of Faith (Name of Allah)",
    origin: "Arabic",
    pronunciation: "Al-Mu-min",
    gender: "boy",
    status: "forbidden",
    quranic: false,
},
{
    id: 194,
    english: "Al-Muhsi",
    arabic: "المحصي",
    urdu: "المحصی",
    persian: "المحصی",
    meaning: "The Reckoner (Name of Allah)",
    origin: "Arabic",
    pronunciation: "Al-Muh-see",
    gender: "boy",
    status: "forbidden",
    quranic: false,
},
{
    id: 195,
    english: "Al-Mubdi",
    arabic: "المبدئ",
    urdu: "المبدئ",
    persian: "المبدئ",
    meaning: "The Originator (Name of Allah)",
    origin: "Arabic",
    pronunciation: "Al-Mub-dee",
    gender: "boy",
    status: "forbidden",
    quranic: false,
},
{
    id: 196,
    english: "Al-Mu'id",
    arabic: "المعيد",
    urdu: "المعید",
    persian: "المعید",
    meaning: "The Restorer (Name of Allah)",
    origin: "Arabic",
    pronunciation: "Al-Mu-eed",
    gender: "boy",
    status: "forbidden",
    quranic: false,
},
{
    id: 197,
    english: "Al-Muhyi",
    arabic: "المحيي",
    urdu: "المحیی",
    persian: "المحیی",
    meaning: "The Giver of Life (Name of Allah)",
    origin: "Arabic",
    pronunciation: "Al-Muh-yee",
    gender: "boy",
    status: "forbidden",
    quranic: false,
},
{
    id: 198,
    english: "Al-Mumit",
    arabic: "المميت",
    urdu: "الممیت",
    persian: "الممیت",
    meaning: "The Bringer of Death (Name of Allah)",
    origin: "Arabic",
    pronunciation: "Al-Mu-meet",
    gender: "boy",
    status: "forbidden",
    quranic: false,
},
{
    id: 199,
    english: "Al-Hayy",
    arabic: "الحي",
    urdu: "الحی",
    persian: "الحی",
    meaning: "The Ever-Living (Name of Allah)",
    origin: "Arabic",
    pronunciation: "Al-Hayy",
    gender: "boy",
    status: "forbidden",
    quranic: false,
},
{
    id: 200,
    english: "Al-Qayyum",
    arabic: "القيوم",
    urdu: "القیوم",
    persian: "القیوم",
    meaning: "The Sustainer (Name of Allah)",
    origin: "Arabic",
    pronunciation: "Al-Qay-yoom",
    gender: "boy",
    status: "forbidden",
    quranic: false,
},
{
    id: 201,
    english: "Aahil",
    arabic: "آہل",
    urdu: "آہل",
    persian: "آهل",
    meaning: "Prince, Great Leader",
    origin: "Urdu",
    pronunciation: "Aa-hil",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 202,
    english: "Zohan",
    arabic: "زوهان",
    urdu: "زوہان",
    persian: "زوهان",
    meaning: "Light of the World",
    origin: "Urdu",
    pronunciation: "Zo-han",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 203,
    english: "Zaviyar",
    arabic: "زافيار",
    urdu: "زویار",
    persian: "زویار",
    meaning: "Light, Bright",
    origin: "Urdu",
    pronunciation: "Za-vi-yar",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 204,
    english: "Alaya",
    arabic: "عالية",
    urdu: "عالیہ",
    persian: "عالیه",
    meaning: "Sublime, Exalted",
    origin: "Urdu",
    pronunciation: "A-la-ya",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 205,
    english: "Zidan",
    arabic: "زيدان",
    urdu: "زیدان",
    persian: "زیدان",
    meaning: "Growth, Abundance",
    origin: "Urdu",
    pronunciation: "Zi-dan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 206,
    english: "Hoorain",
    arabic: "حورين",
    urdu: "حورین",
    persian: "حورین",
    meaning: "Beautiful Eyes like Houri",
    origin: "Urdu",
    pronunciation: "Hoo-rain",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 207,
    english: "Aizah",
    arabic: "عائزة",
    urdu: "عائزہ",
    persian: "عائزه",
    meaning: "Respected, Noble",
    origin: "Urdu",
    pronunciation: "Ai-zah",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 208,
    english: "Zaryan",
    arabic: "زاريان",
    urdu: "زاریان",
    persian: "زاریان",
    meaning: "Golden, Precious",
    origin: "Urdu",
    pronunciation: "Zar-yan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 209,
    english: "Rohaan",
    arabic: "روهان",
    urdu: "روحان",
    persian: "روحان",
    meaning: "Soul, Spiritual",
    origin: "Urdu",
    pronunciation: "Ro-haan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 210,
    english: "Zunaira",
    arabic: "زنيّرة",
    urdu: "زنینہ",
    persian: "زنینه",
    meaning: "Guiding Light",
    origin: "Urdu",
    pronunciation: "Zu-nai-ra",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 211,
    english: "Abeer",
    arabic: "عبير",
    urdu: "عبیر",
    persian: "عبیر",
    meaning: "Fragrance, Scent",
    origin: "Urdu",
    pronunciation: "A-beer",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 212,
    english: "Zohaib",
    arabic: "زهيب",
    urdu: "زوہیب",
    persian: "زهیب",
    meaning: "Leader, King",
    origin: "Urdu",
    pronunciation: "Zo-haib",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 213,
    english: "Anaya",
    arabic: "عنایا",
    urdu: "عنایا",
    persian: "عنایا",
    meaning: "God's Answer",
    origin: "Urdu",
    pronunciation: "A-na-ya",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 214,
    english: "Zaryab",
    arabic: "زارياب",
    urdu: "زاریاب",
    persian: "زاریاب",
    meaning: "Golden Water",
    origin: "Urdu",
    pronunciation: "Zar-yab",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 215,
    english: "Izza",
    arabic: "عزة",
    urdu: "عزہ",
    persian: "عزه",
    meaning: "Honor, Respect",
    origin: "Urdu",
    pronunciation: "Iz-za",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 216,
    english: "Rumaisa",
    arabic: "رميسة",
    urdu: "رمیسہ",
    persian: "رمیسه",
    meaning: "Graceful, Beautiful",
    origin: "Urdu",
    pronunciation: "Ru-mai-sa",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 217,
    english: "Zaeem",
    arabic: "زعيم",
    urdu: "زعیم",
    persian: "زعیم",
    meaning: "Leader, Chief",
    origin: "Urdu",
    pronunciation: "Za-eem",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 218,
    english: "Alishba",
    arabic: "عليشبا",
    urdu: "علیشبا",
    persian: "علیشبا",
    meaning: "Beautiful, Pretty",
    origin: "Urdu",
    pronunciation: "A-lish-ba",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 219,
    english: "Zorain",
    arabic: "زورين",
    urdu: "زورین",
    persian: "زورین",
    meaning: "Beautiful Flower",
    origin: "Urdu",
    pronunciation: "Zo-rain",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 220,
    english: "Areej",
    arabic: "عريج",
    urdu: "عریج",
    persian: "عریج",
    meaning: "Fragrance, Scent",
    origin: "Urdu",
    pronunciation: "A-reej",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 221,
    english: "Zavian",
    arabic: "زافيان",
    urdu: "زافیان",
    persian: "زافیان",
    meaning: "Bright, Shining",
    origin: "Urdu",
    pronunciation: "Za-vi-an",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 222,
    english: "Anabia",
    arabic: "أنابيا",
    urdu: "انابیہ",
    persian: "انابیا",
    meaning: "Door of Heaven",
    origin: "Urdu",
    pronunciation: "A-na-bia",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 223,
    english: "Zoraiz",
    arabic: "زوريز",
    urdu: "زوریز",
    persian: "زوریز",
    meaning: "Shining Star",
    origin: "Urdu",
    pronunciation: "Zo-raiz",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 224,
    english: "Zoha",
    arabic: "زہى",
    urdu: "زوہا",
    persian: "زوها",
    meaning: "Light, Dawn",
    origin: "Urdu",
    pronunciation: "Zo-ha",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 225,
    english: "Zayan",
    arabic: "زايان",
    urdu: "زایان",
    persian: "زایان",
    meaning: "Beautiful, Graceful",
    origin: "Urdu",
    pronunciation: "Za-yan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 226,
    english: "Inara",
    arabic: "إنارة",
    urdu: "انارہ",
    persian: "اناره",
    meaning: "Heavenly Light",
    origin: "Urdu",
    pronunciation: "I-na-ra",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 227,
    english: "Zohaib",
    arabic: "زهيب",
    urdu: "زوہیب",
    persian: "زهیب",
    meaning: "Leader, King",
    origin: "Urdu",
    pronunciation: "Zo-haib",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 228,
    english: "Arisha",
    arabic: "عريشة",
    urdu: "عریشہ",
    persian: "عریشه",
    meaning: "Peaceful, Living",
    origin: "Urdu",
    pronunciation: "A-ri-sha",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 229,
    english: "Zimal",
    arabic: "زمل",
    urdu: "زمل",
    persian: "زمل",
    meaning: "Garment, Covering",
    origin: "Urdu",
    pronunciation: "Zi-mal",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 230,
    english: "Rayyan",
    arabic: "ريّان",
    urdu: "ریان",
    persian: "ریان",
    meaning: "Gate of Paradise",
    origin: "Urdu",
    pronunciation: "Ray-yan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 231,
    english: "Wasif",
    arabic: "واصف",
    urdu: "واصف",
    persian: "واصف",
    meaning: "One who describes, Narrator",
    origin: "Arabic",
    pronunciation: "Wa-sif",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 232,
    english: "Nadira",
    arabic: "نديرة",
    urdu: "ندیرہ",
    persian: "ندیره",
    meaning: "Rare, Precious",
    origin: "Arabic",
    pronunciation: "Na-di-ra",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 233,
    english: "Basheer",
    arabic: "بشير",
    urdu: "بشیر",
    persian: "بشیر",
    meaning: "Bringer of Good News",
    origin: "Arabic",
    pronunciation: "Ba-sheer",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Al-A'raf 7:188"
},
{
    id: 234,
    english: "Zahraa",
    arabic: "زهراء",
    urdu: "زہرا",
    persian: "زهرا",
    meaning: "Brilliant, Shining",
    origin: "Arabic",
    pronunciation: "Zah-raa",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 235,
    english: "Muneer",
    arabic: "منير",
    urdu: "منیر",
    persian: "منیر",
    meaning: "Illuminating, Radiant",
    origin: "Arabic",
    pronunciation: "Mu-neer",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Al-Ahzab 33:46"
},
{
    id: 236,
    english: "Suhaila",
    arabic: "سهيلة",
    urdu: "سہیلہ",
    persian: "سهیله",
    meaning: "Smooth, Easy, Gentle",
    origin: "Arabic",
    pronunciation: "Su-hai-la",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 237,
    english: "Jaseem",
    arabic: "جمسم",
    urdu: "جمسم",
    persian: "جمسم",
    meaning: "Great, Vast, Impressive",
    origin: "Arabic",
    pronunciation: "Ja-seem",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 238,
    english: "Nawfal",
    arabic: "نوفل",
    urdu: "نوفل",
    persian: "نوفل",
    meaning: "Generous, Sea",
    origin: "Arabic",
    pronunciation: "Naw-fal",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 239,
    english: "Dilshad",
    arabic: "ديلشاد",
    urdu: "دلشاد",
    persian: "دلشاد",
    meaning: "Happy Heart, Cheerful",
    origin: "Persian",
    pronunciation: "Dil-shad",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 240,
    english: "Firoza",
    arabic: "فيروزة",
    urdu: "فیروزہ",
    persian: "فیروزه",
    meaning: "Turquoise, Victorious",
    origin: "Persian",
    pronunciation: "Fi-ro-za",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 241,
    english: "Adeel",
    arabic: "عديل",
    urdu: "عدیل",
    persian: "عدیل",
    meaning: "Just, Fair",
    origin: "Arabic",
    pronunciation: "A-deel",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 242,
    english: "Munira",
    arabic: "منيرة",
    urdu: "منیرہ",
    persian: "منیره",
    meaning: "Illuminating, Bright",
    origin: "Arabic",
    pronunciation: "Mu-ni-ra",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 243,
    english: "Sajid",
    arabic: "ساجد",
    urdu: "ساجد",
    persian: "ساجد",
    meaning: "One who Prostrates, Worshipper",
    origin: "Arabic",
    pronunciation: "Sa-jid",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Al-Furqan 25:64"
},
{
    id: 244,
    english: "Wajeeha",
    arabic: "وجيعة",
    urdu: "وجیہہ",
    persian: "وجیعه",
    meaning: "Distinguished, Eminent",
    origin: "Arabic",
    pronunciation: "Wa-jee-ha",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 245,
    english: "Mujahid",
    arabic: "مجاهد",
    urdu: "مجاہد",
    persian: "مجاهد",
    meaning: "Warrior, Striver",
    origin: "Arabic",
    pronunciation: "Mu-ja-hid",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah An-Nisa 4:95"
},
{
    id: 246,
    english: "Nazish",
    arabic: "نازش",
    urdu: "نازش",
    persian: "نازش",
    meaning: "Pride, Elegance",
    origin: "Persian",
    pronunciation: "Na-zish",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 247,
    english: "Rashad",
    arabic: "رشاد",
    urdu: "رشاد",
    persian: "رشاد",
    meaning: "Right Guidance, Integrity",
    origin: "Arabic",
    pronunciation: "Ra-shad",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 248,
    english: "Suhayb",
    arabic: "صهيب",
    urdu: "صہیب",
    persian: "صهیب",
    meaning: "Reddish Hair, Sandy",
    origin: "Arabic",
    pronunciation: "Su-hayb",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 249,
    english: "Zubaydah",
    arabic: "زبيدة",
    urdu: "زبیدہ",
    persian: "زبیده",
    meaning: "Butter, Cream",
    origin: "Arabic",
    pronunciation: "Zu-bay-dah",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 250,
    english: "Murtaza",
    arabic: "مرتضى",
    urdu: "مرتضیٰ",
    persian: "مرتضی",
    meaning: "Chosen, Selected",
    origin: "Arabic",
    pronunciation: "Mur-ta-za",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 251,
    english: "Nazneen",
    arabic: "نازنين",
    urdu: "نازنین",
    persian: "نازنین",
    meaning: "Delicate, Beautiful",
    origin: "Persian",
    pronunciation: "Naz-neen",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 252,
    english: "Shafeeq",
    arabic: "شفیق",
    urdu: "شفیق",
    persian: "شفیق",
    meaning: "Compassionate, Kind",
    origin: "Arabic",
    pronunciation: "Sha-feeq",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 253,
    english: "Umamah",
    arabic: "أمامة",
    urdu: "امامہ",
    persian: "امامه",
    meaning: "Young Mother",
    origin: "Arabic",
    pronunciation: "U-ma-mah",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 254,
    english: "Yaseen",
    arabic: "يٰسٓ",
    urdu: "یٰسٓ",
    persian: "یٰسٓ",
    meaning: "Chapter of Quran",
    origin: "Arabic",
    pronunciation: "Ya-seen",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Ya-Sin 36:1"
},
{
    id: 255,
    english: "Zahid",
    arabic: "زاهد",
    urdu: "زاہد",
    persian: "زاهد",
    meaning: "Ascetic, Devout",
    origin: "Arabic",
    pronunciation: "Za-hid",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 256,
    english: "Nawal",
    arabic: "نوال",
    urdu: "نوال",
    persian: "نوال",
    meaning: "Gift, Present",
    origin: "Arabic",
    pronunciation: "Na-wal",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 257,
    english: "Mubeen",
    arabic: "مبين",
    urdu: "مبین",
    persian: "مبین",
    meaning: "Clear, Evident",
    origin: "Arabic",
    pronunciation: "Mu-been",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah An-Nur 24:1"
},
{
    id: 258,
    english: "Suhayla",
    arabic: "سهیلة",
    urdu: "سہیلہ",
    persian: "سهیله",
    meaning: "Gentle, Smooth",
    origin: "Arabic",
    pronunciation: "Su-hay-la",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 259,
    english: "Waseem",
    arabic: "وسيم",
    urdu: "وسیم",
    persian: "وسیم",
    meaning: "Handsome, Graceful",
    origin: "Arabic",
    pronunciation: "Wa-seem",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 260,
    english: "Nazifa",
    arabic: "نظيفة",
    urdu: "نظیفہ",
    persian: "نظیفه",
    meaning: "Pure, Clean",
    origin: "Arabic",
    pronunciation: "Na-zi-fa",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 261,
    english: "Rashid",
    arabic: "رشيد",
    urdu: "رشید",
    persian: "رشید",
    meaning: "Rightly Guided",
    origin: "Arabic",
    pronunciation: "Ra-sheed",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Hud 11:78"
},
{
    id: 262,
    english: "Suhayr",
    arabic: "سهير",
    urdu: "سہیر",
    persian: "سهیر",
    meaning: "Small Rock, Name of Sahabiya",
    origin: "Arabic",
    pronunciation: "Su-hayr",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 263,
    english: "Zafar",
    arabic: "ظفر",
    urdu: "ظفر",
    persian: "ظفر",
    meaning: "Victory, Triumph",
    origin: "Arabic",
    pronunciation: "Za-far",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 264,
    english: "Nadim",
    arabic: "نديم",
    urdu: "ندیم",
    persian: "ندیم",
    meaning: "Friend, Companion",
    origin: "Arabic",
    pronunciation: "Na-dim",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 265,
    english: "Mumtaz",
    arabic: "ممتاز",
    urdu: "ممتاز",
    persian: "ممتاز",
    meaning: "Excellent, Distinguished",
    origin: "Arabic",
    pronunciation: "Mum-taz",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 266,
    english: "Nazira",
    arabic: "نظيرة",
    urdu: "نظیرہ",
    persian: "نظیره",
    meaning: "Observer, Supervisor",
    origin: "Arabic",
    pronunciation: "Na-zi-ra",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 267,
    english: "Sadiq",
    arabic: "صادق",
    urdu: "صادق",
    persian: "صادق",
    meaning: "Truthful, Honest",
    origin: "Arabic",
    pronunciation: "Sa-diq",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 268,
    english: "Zahira",
    arabic: "ظاهرة",
    urdu: "ظاہرہ",
    persian: "ظاهره",
    meaning: "Evident, Manifest",
    origin: "Arabic",
    pronunciation: "Za-hi-ra",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 269,
    english: "Nawaz",
    arabic: "نواز",
    urdu: "نواز",
    persian: "نواز",
    meaning: "Caretaker, One who Grants",
    origin: "Persian",
    pronunciation: "Na-waz",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 270,
    english: "Musharraf",
    arabic: "مشرف",
    urdu: "مشرف",
    persian: "مشرف",
    meaning: "Honored, Exalted",
    origin: "Arabic",
    pronunciation: "Mu-shar-raf",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 271,
    english: "Nazli",
    arabic: "نازلي",
    urdu: "نازلی",
    persian: "نازلی",
    meaning: "Delicate, Beautiful",
    origin: "Persian",
    pronunciation: "Naz-li",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 272,
    english: "Safwat",
    arabic: "صفوت",
    urdu: "صفوت",
    persian: "صفوت",
    meaning: "Best, Choicest",
    origin: "Arabic",
    pronunciation: "Saf-wat",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 273,
    english: "Zaki",
    arabic: "زكي",
    urdu: "زکی",
    persian: "زکی",
    meaning: "Pure, Intelligent",
    origin: "Arabic",
    pronunciation: "Za-ki",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 274,
    english: "Nahla",
    arabic: "نهلة",
    urdu: "نہلہ",
    persian: "نهله",
    meaning: "Water in Desert, Gift",
    origin: "Arabic",
    pronunciation: "Nah-la",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 275,
    english: "Mujtaba",
    arabic: "مجتبى",
    urdu: "مجتبیٰ",
    persian: "مجتبی",
    meaning: "Chosen, Selected",
    origin: "Arabic",
    pronunciation: "Muj-ta-ba",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 276,
    english: "Nazakat",
    arabic: "نزاکت",
    urdu: "نزاکت",
    persian: "نزاکت",
    meaning: "Elegance, Delicacy",
    origin: "Persian",
    pronunciation: "Na-za-kat",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 277,
    english: "Sahir",
    arabic: "ساحر",
    urdu: "ساحر",
    persian: "ساحر",
    meaning: "Wakeful, Magician",
    origin: "Arabic",
    pronunciation: "Sa-hir",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 278,
    english: "Zarina",
    arabic: "زارينة",
    urdu: "زارینہ",
    persian: "زارینه",
    meaning: "Golden, Made of Gold",
    origin: "Persian",
    pronunciation: "Za-ri-na",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 279,
    english: "Nawid",
    arabic: "ناويد",
    urdu: "ناوید",
    persian: "ناوید",
    meaning: "Good News",
    origin: "Persian",
    pronunciation: "Na-wid",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 280,
    english: "Mudassir",
    arabic: "مدثر",
    urdu: "مدثر",
    persian: "مدثر",
    meaning: "Wrapped in Cloak",
    origin: "Arabic",
    pronunciation: "Mu-das-sir",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Al-Muddathir 74:1"
},
{
    id: 281,
    english: "Nazmin",
    arabic: "نازمين",
    urdu: "نازمین",
    persian: "نازمین",
    meaning: "Princess, Delicate",
    origin: "Persian",
    pronunciation: "Naz-min",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 282,
    english: "Sajjad",
    arabic: "سجاد",
    urdu: "سجاد",
    persian: "سجاد",
    meaning: "One who Prostrates Often",
    origin: "Arabic",
    pronunciation: "Saj-jad",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 283,
    english: "Zarrin",
    arabic: "زرين",
    urdu: "زرین",
    persian: "زرین",
    meaning: "Golden",
    origin: "Persian",
    pronunciation: "Zar-rin",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 284,
    english: "Nawshad",
    arabic: "نوشاد",
    urdu: "نوشاد",
    persian: "نوشاد",
    meaning: "Happy, Joyful",
    origin: "Persian",
    pronunciation: "Naw-shad",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 285,
    english: "Mufeed",
    arabic: "مفيد",
    urdu: "مفید",
    persian: "مفید",
    meaning: "Useful, Beneficial",
    origin: "Arabic",
    pronunciation: "Mu-feed",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 286,
    english: "Naznin",
    arabic: "نازنين",
    urdu: "نازنین",
    persian: "نازنین",
    meaning: "Delicate, Beautiful",
    origin: "Persian",
    pronunciation: "Naz-nin",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 287,
    english: "Saleem",
    arabic: "سليم",
    urdu: "سلیم",
    persian: "سلیم",
    meaning: "Peaceful, Safe",
    origin: "Arabic",
    pronunciation: "Sa-leem",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Ash-Shu'ara 26:89"
},
{
    id: 288,
    english: "Zaynab",
    arabic: "زينب",
    urdu: "زینب",
    persian: "زینب",
    meaning: "Fragrant Flower",
    origin: "Arabic",
    pronunciation: "Zay-nab",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 289,
    english: "Nawwar",
    arabic: "نوار",
    urdu: "نوار",
    persian: "نوار",
    meaning: "Flower, Blossom",
    origin: "Arabic",
    pronunciation: "Naw-war",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 290,
    english: "Mujib",
    arabic: "مجيب",
    urdu: "مجیب",
    persian: "مجیب",
    meaning: "Responsive, Answerer",
    origin: "Arabic",
    pronunciation: "Mu-jib",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 291,
    english: "Nazraana",
    arabic: "نزرانة",
    urdu: "نذرانہ",
    persian: "نذرانه",
    meaning: "Gift, Present",
    origin: "Persian",
    pronunciation: "Naz-raa-na",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 292,
    english: "Samir",
    arabic: "سمير",
    urdu: "سمیر",
    persian: "سمیر",
    meaning: "Entertaining Companion",
    origin: "Arabic",
    pronunciation: "Sa-mir",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 293,
    english: "Zeba",
    arabic: "زيبا",
    urdu: "زیبا",
    persian: "زیبا",
    meaning: "Beautiful, Pretty",
    origin: "Persian",
    pronunciation: "Ze-ba",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 294,
    english: "Nayab",
    arabic: "نياب",
    urdu: "نیاب",
    persian: "نیاب",
    meaning: "Rare, Precious",
    origin: "Persian",
    pronunciation: "Na-yab",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 295,
    english: "Muneeb",
    arabic: "منيب",
    urdu: "منیب",
    persian: "منیب",
    meaning: "One who Turns to God",
    origin: "Arabic",
    pronunciation: "Mu-neeb",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 296,
    english: "Nazuk",
    arabic: "نازك",
    urdu: "نازک",
    persian: "نازک",
    meaning: "Delicate, Soft",
    origin: "Persian",
    pronunciation: "Na-zuk",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 297,
    english: "Shakeel",
    arabic: "شکیل",
    urdu: "شکیل",
    persian: "شکیل",
    meaning: "Handsome, Good-Looking",
    origin: "Arabic",
    pronunciation: "Sha-keel",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 298,
    english: "Zeenat",
    arabic: "زينت",
    urdu: "زینت",
    persian: "زینت",
    meaning: "Beauty, Adornment",
    origin: "Arabic",
    pronunciation: "Zee-nat",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 299,
    english: "Nazir",
    arabic: "نظير",
    urdu: "نظیر",
    persian: "نظیر",
    meaning: "Observer, Warner",
    origin: "Arabic",
    pronunciation: "Na-zir",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 300,
    english: "Mushfiq",
    arabic: "مشفق",
    urdu: "مشفق",
    persian: "مشفق",
    meaning: "Compassionate, Kind",
    origin: "Arabic",
    pronunciation: "Mush-fiq",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 301,
    english: "Naziya",
    arabic: "نازية",
    urdu: "نازیہ",
    persian: "نازیه",
    meaning: "Proud, Beautiful",
    origin: "Arabic",
    pronunciation: "Na-zi-ya",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 302,
    english: "Shamim",
    arabic: "شميم",
    urdu: "شمیم",
    persian: "شمیم",
    meaning: "Fragrant, Aroma",
    origin: "Arabic",
    pronunciation: "Sha-mim",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 303,
    english: "Zara",
    arabic: "زارا",
    urdu: "زارا",
    persian: "زارا",
    meaning: "Princess, Radiance",
    origin: "Arabic",
    pronunciation: "Za-ra",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 304,
    english: "Nazakat",
    arabic: "نزاکت",
    urdu: "نزاکت",
    persian: "نزاکت",
    meaning: "Elegance, Grace",
    origin: "Persian",
    pronunciation: "Na-za-kat",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 305,
    english: "Mustafa",
    arabic: "مصطفى",
    urdu: "مصطفیٰ",
    persian: "مصطفی",
    meaning: "Chosen, Selected",
    origin: "Arabic",
    pronunciation: "Mus-ta-fa",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Taha 20:13"
},
{
    id: 306,
    english: "Nazmoon",
    arabic: "نظمون",
    urdu: "نظمون",
    persian: "نظمون",
    meaning: "Organized, Systematic",
    origin: "Arabic",
    pronunciation: "Naz-moon",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 307,
    english: "Shahid",
    arabic: "شهيد",
    urdu: "شہید",
    persian: "شهید",
    meaning: "Witness, Martyr",
    origin: "Arabic",
    pronunciation: "Sha-hid",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Al-Baqarah 2:143"
},
{
    id: 308,
    english: "Zohra",
    arabic: "زهرة",
    urdu: "زہرہ",
    persian: "زهره",
    meaning: "Venus, Flower",
    origin: "Arabic",
    pronunciation: "Zoh-ra",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 309,
    english: "Nazneen",
    arabic: "نازنين",
    urdu: "نازنین",
    persian: "نازنین",
    meaning: "Delicate, Beautiful",
    origin: "Persian",
    pronunciation: "Naz-neen",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 310,
    english: "Mutahir",
    arabic: "مطهر",
    urdu: "مطہر",
    persian: "مطهر",
    meaning: "Pure, Clean",
    origin: "Arabic",
    pronunciation: "Mu-ta-hir",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 311,
    english: "Nazpara",
    arabic: "نازپارا",
    urdu: "نازپارہ",
    persian: "نازپارا",
    meaning: "Beloved, Darling",
    origin: "Persian",
    pronunciation: "Naz-pa-ra",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 312,
    english: "Shahzad",
    arabic: "شهزاد",
    urdu: "شہزاد",
    persian: "شهزاد",
    meaning: "Prince",
    origin: "Persian",
    pronunciation: "Shah-zad",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 313,
    english: "Zulekha",
    arabic: "زليخة",
    urdu: "زلیخا",
    persian: "زلیخا",
    meaning: "Fair, Brilliant",
    origin: "Arabic",
    pronunciation: "Zu-le-kha",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 314,
    english: "Nazrana",
    arabic: "نذرانة",
    urdu: "نذرانہ",
    persian: "نذرانه",
    meaning: "Gift, Present",
    origin: "Persian",
    pronunciation: "Naz-ra-na",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 315,
    english: "Naeem",
    arabic: "نعيم",
    urdu: "نعیم",
    persian: "نعیم",
    meaning: "Comfort, Blessing",
    origin: "Arabic",
    pronunciation: "Na-eem",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Al-Ma'idah 5:65"
},
{
    id: 316,
    english: "Nazish",
    arabic: "نازش",
    urdu: "نازش",
    persian: "نازش",
    meaning: "Pride, Beauty",
    origin: "Persian",
    pronunciation: "Na-zish",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 317,
    english: "Shuja",
    arabic: "شجاع",
    urdu: "شجاع",
    persian: "شجاع",
    meaning: "Brave, Courageous",
    origin: "Arabic",
    pronunciation: "Shu-ja",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 318,
    english: "Zumurrud",
    arabic: "زمرد",
    urdu: "زمرد",
    persian: "زمرد",
    meaning: "Emerald",
    origin: "Arabic",
    pronunciation: "Zu-mur-rud",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 319,
    english: "Nazakat",
    arabic: "نزاکت",
    urdu: "نزاکت",
    persian: "نزاکت",
    meaning: "Elegance, Grace",
    origin: "Persian",
    pronunciation: "Na-za-kat",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 320,
    english: "Nawab",
    arabic: "نواب",
    urdu: "نواب",
    persian: "نواب",
    meaning: "Prince, Nobleman",
    origin: "Arabic",
    pronunciation: "Na-wab",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 321,
    english: "Nazneen",
    arabic: "نازنين",
    urdu: "نازنین",
    persian: "نازنین",
    meaning: "Delicate, Beautiful",
    origin: "Persian",
    pronunciation: "Naz-neen",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 322,
    english: "Siraj",
    arabic: "سراج",
    urdu: "سراج",
    persian: "سراج",
    meaning: "Lamp, Light",
    origin: "Arabic",
    pronunciation: "Si-raj",
    gender: "boy",
    status: "allowed",
    quranic: true,
    ayah: "Surah Al-Ahzab 33:46"
},
{
    id: 323,
    english: "Zahida",
    arabic: "زاهدة",
    urdu: "زاہدہ",
    persian: "زاهاده",
    meaning: "Devout, Ascetic",
    origin: "Arabic",
    pronunciation: "Za-hi-da",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 324,
    english: "Nazakat",
    arabic: "نزاکت",
    urdu: "نزاکت",
    persian: "نزاکت",
    meaning: "Elegance, Delicacy",
    origin: "Persian",
    pronunciation: "Na-za-kat",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 325,
    english: "Nawshaba",
    arabic: "نوشابا",
    urdu: "نوشابا",
    persian: "نوشابا",
    meaning: "Elixir, Nectar",
    origin: "Persian",
    pronunciation: "Naw-sha-ba",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 326,
    english: "Nazneen",
    arabic: "نازنين",
    urdu: "نازنین",
    persian: "نازنین",
    meaning: "Delicate, Beautiful",
    origin: "Persian",
    pronunciation: "Naz-neen",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 327,
    english: "Tahir",
    arabic: "طاهر",
    urdu: "طاہر",
    persian: "طاهر",
    meaning: "Pure, Chaste",
    origin: "Arabic",
    pronunciation: "Ta-hir",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 328,
    english: "Zara",
    arabic: "زارا",
    urdu: "زارا",
    persian: "زارا",
    meaning: "Princess, Radiance",
    origin: "Arabic",
    pronunciation: "Za-ra",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 329,
    english: "Nazakat",
    arabic: "نزاکت",
    urdu: "نزاکت",
    persian: "نزاکت",
    meaning: "Elegance, Grace",
    origin: "Persian",
    pronunciation: "Na-za-kat",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 330,
    english: "Nawfal",
    arabic: "نوفل",
    urdu: "نوفل",
    persian: "نوفل",
    meaning: "Generous, Sea",
    origin: "Arabic",
    pronunciation: "Naw-fal",
    gender: "boy",
    status: "allowed",
    quranic: false
},

        ];