const normalNames = [
    {
        id: 1,
        english: "Aisha",
        arabic: "عائشة",
        urdu: "عائشہ",
        persian: "عایشه",
        meaning: "Living, Prosperous",
        origin: "Arabic",
        pronunciation: "Aa-ee-sha",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 2,
        english: "Fatima",
        arabic: "فاطمة",
        urdu: "فاطمہ",
        persian: "فاطمه",
        meaning: "Weaning, Abstaining",
        origin: "Arabic",
        pronunciation: "Faa-ti-ma",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 3,
        english: "Zainab",
        arabic: "زينب",
        urdu: "زینب",
        persian: "زینب",
        meaning: "Fragrant Flower",
        origin: "Arabic",
        pronunciation: "Zay-nab",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 4,
        english: "Ali",
        arabic: "علي",
        urdu: "علی",
        persian: "علی",
        meaning: "Exalted, Noble",
        origin: "Arabic",
        pronunciation: "Aa-lee",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 5,
        english: "Omar",
        arabic: "عمر",
        urdu: "عمر",
        persian: "عمر",
        meaning: "Long-Lived",
        origin: "Arabic",
        pronunciation: "O-mar",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 6,
        english: "Khadija",
        arabic: "خديجة",
        urdu: "خدیجہ",
        persian: "خدیجه",
        meaning: "Premature Child",
        origin: "Arabic",
        pronunciation: "Kha-dee-ja",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 7,
        english: "Amina",
        arabic: "آمنة",
        urdu: "آمنہ",
        persian: "آمنه",
        meaning: "Trustworthy, Peaceful",
        origin: "Arabic",
        pronunciation: "Aa-mee-na",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 8,
        english: "Hafsa",
        arabic: "حفصة",
        urdu: "حفصہ",
        persian: "حفصه",
        meaning: "Young Lioness",
        origin: "Arabic",
        pronunciation: "Haf-sa",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 9,
        english: "Safia",
        arabic: "صفية",
        urdu: "صفیہ",
        persian: "صفیه",
        meaning: "Pure, Best Friend",
        origin: "Arabic",
        pronunciation: "Sa-fee-ya",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 10,
        english: "Bilal",
        arabic: "بلال",
        urdu: "بلال",
        persian: "بلال",
        meaning: "Moistening, Refreshing",
        origin: "Arabic",
        pronunciation: "Bee-lal",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 11,
        english: "Asma",
        arabic: "أسماء",
        urdu: "اسماء",
        persian: "اسماء",
        meaning: "Supreme, Lofty",
        origin: "Arabic",
        pronunciation: "As-maa",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 12,
        english: "Ruqayya",
        arabic: "رقية",
        urdu: "رقّیہ",
        persian: "رقیه",
        meaning: "Rising, Ascending",
        origin: "Arabic",
        pronunciation: "Roo-qay-ya",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 13,
        english: "Abdullah",
        arabic: "عبد الله",
        urdu: "عبداللہ",
        persian: "عبدالله",
        meaning: "Servant of God",
        origin: "Arabic",
        pronunciation: "Ab-dul-lah",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 14,
        english: "Sumayya",
        arabic: "سمية",
        urdu: "سمیہ",
        persian: "سمیه",
        meaning: "High Above, Elevated",
        origin: "Arabic",
        pronunciation: "Su-may-ya",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 15,
        english: "Hamza",
        arabic: "حمزة",
        urdu: "حمزہ",
        persian: "حمزه",
        meaning: "Lion, Strong",
        origin: "Arabic",
        pronunciation: "Ham-za",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 16,
        english: "Jameela",
        arabic: "جميلة",
        urdu: "جمیلہ",
        persian: "جمیله",
        meaning: "Beautiful",
        origin: "Arabic",
        pronunciation: "Ja-mee-la",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 17,
        english: "Hussain",
        arabic: "حسين",
        urdu: "حسین",
        persian: "حسین",
        meaning: "Handsome, Beautiful",
        origin: "Arabic",
        pronunciation: "Hus-sain",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 18,
        english: "Hasan",
        arabic: "حسن",
        urdu: "حسن",
        persian: "حسن",
        meaning: "Handsome, Good",
        origin: "Arabic",
        pronunciation: "Ha-san",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 19,
        english: "Talha",
        arabic: "طلحة",
        urdu: "طلحہ",
        persian: "طلحه",
        meaning: "Fruitful Tree",
        origin: "Arabic",
        pronunciation: "Tal-ha",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 20,
        english: "Zubair",
        arabic: "زبیر",
        urdu: "زبیر",
        persian: "زبیر",
        meaning: "Strong, Powerful",
        origin: "Arabic",
        pronunciation: "Zoo-bair",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 21,
        english: "Saad",
        arabic: "سعد",
        urdu: "سعد",
        persian: "سعد",
        meaning: "Good Fortune, Lucky",
        origin: "Arabic",
        pronunciation: "Sa-ad",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 22,
        english: "Saeed",
        arabic: "سعید",
        urdu: "سعید",
        persian: "سعید",
        meaning: "Happy, Fortunate",
        origin: "Arabic",
        pronunciation: "Saa-eed",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 23,
        english: "Faris",
        arabic: "فارس",
        urdu: "فارس",
        persian: "فارس",
        meaning: "Knight, Horseman",
        origin: "Arabic",
        pronunciation: "Faa-ris",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 24,
        english: "Jafar",
        arabic: "جعفر",
        urdu: "جعفر",
        persian: "جعفر",
        meaning: "Stream, River",
        origin: "Arabic",
        pronunciation: "Jaa-far",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 25,
        english: "Khalid",
        arabic: "خالد",
        urdu: "خالد",
        persian: "خالد",
        meaning: "Eternal, Immortal",
        origin: "Arabic",
        pronunciation: "Khaa-lid",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 26,
        english: "Waleed",
        arabic: "ولید",
        urdu: "ولید",
        persian: "ولید",
        meaning: "Newborn Child",
        origin: "Arabic",
        pronunciation: "Waa-leed",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 27,
        english: "Sarah",
        arabic: "سارة",
        urdu: "سارہ",
        persian: "سارا",
        meaning: "Princess, Pure",
        origin: "Arabic",
        pronunciation: "Saa-rah",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 28,
        english: "Hajar",
        arabic: "هاجر",
        urdu: "ہاجر",
        persian: "هاجر",
        meaning: "Emigrant, One Who Migrates",
        origin: "Arabic",
        pronunciation: "Haa-jar",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 29,
        english: "Safiya",
        arabic: "صفیة",
        urdu: "صفیہ",
        persian: "صفیه",
        meaning: "Pure, Best Friend",
        origin: "Arabic",
        pronunciation: "Sa-fee-ya",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 30,
        english: "Layla",
        arabic: "لیلى",
        urdu: "لیلیٰ",
        persian: "لیلا",
        meaning: "Night, Dark Beauty",
        origin: "Arabic",
        pronunciation: "Lai-la",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 31,
        english: "Hooriya",
        arabic: "حورية",
        urdu: "حوریہ",
        persian: "حوریه",
        meaning: "Angel of Paradise",
        origin: "Arabic",
        pronunciation: "Hoo-ri-ya",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 32,
        english: "Ayesha",
        arabic: "عائشة",
        urdu: "عائشہ",
        persian: "عایشه",
        meaning: "Living, Prosperous",
        origin: "Arabic",
        pronunciation: "Aa-ye-sha",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 33,
        english: "Rabia",
        arabic: "رابعة",
        urdu: "رابعہ",
        persian: "رابعه",
        meaning: "Fourth, Spring",
        origin: "Arabic",
        pronunciation: "Ra-bia",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 34,
        english: "Zara",
        arabic: "زارا",
        urdu: "زارا",
        persian: "زارا",
        meaning: "Princess, Flower",
        origin: "Arabic",
        pronunciation: "Zaa-ra",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 35,
        english: "Yasmin",
        arabic: "ياسمين",
        urdu: "یاسمین",
        persian: "یاسمین",
        meaning: "Jasmine Flower",
        origin: "Arabic",
        pronunciation: "Yas-min",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 36,
        english: "Nadia",
        arabic: "نادية",
        urdu: "نادیہ",
        persian: "نادیه",
        meaning: "Caller, Announcer",
        origin: "Arabic",
        pronunciation: "Naa-dia",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 37,
        english: "Samira",
        arabic: "سميرة",
        urdu: "سمیرہ",
        persian: "سمیرا",
        meaning: "Entertaining Companion",
        origin: "Arabic",
        pronunciation: "Sa-mee-ra",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 38,
        english: "Farida",
        arabic: "فريدة",
        urdu: "فریدہ",
        persian: "فریده",
        meaning: "Unique, Precious",
        origin: "Arabic",
        pronunciation: "Fa-ree-da",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 39,
        english: "Habiba",
        arabic: "حبيبة",
        urdu: "حبیبہ",
        persian: "حبیبه",
        meaning: "Beloved, Darling",
        origin: "Arabic",
        pronunciation: "Ha-bee-ba",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 40,
        english: "Karima",
        arabic: "كريمة",
        urdu: "کریمہ",
        persian: "کریمه",
        meaning: "Generous, Noble",
        origin: "Arabic",
        pronunciation: "Ka-ree-ma",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 41,
        english: "Latifa",
        arabic: "لطيفة",
        urdu: "لطیفہ",
        persian: "لطیفه",
        meaning: "Gentle, Kind",
        origin: "Arabic",
        pronunciation: "La-tee-fa",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 42,
        english: "Naima",
        arabic: "نعيمة",
        urdu: "نعیمہ",
        persian: "نعیمه",
        meaning: "Tranquil, Peaceful",
        origin: "Arabic",
        pronunciation: "Naa-ee-ma",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 43,
        english: "Rukhsar",
        arabic: "روخسار",
        urdu: "رخسار",
        persian: "رخسار",
        meaning: "Cheek, Beautiful Face",
        origin: "Persian",
        pronunciation: "Rukh-saar",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 44,
        english: "Basil",
        arabic: "باسل",
        urdu: "باسل",
        persian: "باسل",
        meaning: "Brave, Valiant",
        origin: "Arabic",
        pronunciation: "Ba-sil",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 45,
        english: "Dania",
        arabic: "دانیا",
        urdu: "دانیا",
        persian: "دانیا",
        meaning: "Close, Near; Wise Woman",
        origin: "Arabic",
        pronunciation: "Da-ni-ya",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 46,
        english: "Farhan",
        arabic: "فرحان",
        urdu: "فرحان",
        persian: "فرحان",
        meaning: "Happy, Joyful",
        origin: "Arabic",
        pronunciation: "Far-han",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 47,
        english: "Gulzar",
        arabic: "گلزار",
        urdu: "گلزار",
        persian: "گلزار",
        meaning: "Garden of Flowers, Blossoming",
        origin: "Persian",
        pronunciation: "Gul-zar",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 48,
        english: "Hadiya",
        arabic: "هادية",
        urdu: "ہادیہ",
        persian: "هادیه",
        meaning: "Guidance; Gifted, Guided",
        origin: "Arabic",
        pronunciation: "Ha-di-ya",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 49,
        english: "Ibtisam",
        arabic: "ابتسام",
        urdu: "ابتسام",
        persian: "ابتسام",
        meaning: "Smile, Cheerful Face",
        origin: "Arabic",
        pronunciation: "Ib-ti-sam",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 50,
        english: "Jawad",
        arabic: "جواد",
        urdu: "جواد",
        persian: "جواد",
        meaning: "Generous, Noble",
        origin: "Arabic",
        pronunciation: "Ja-wad",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 51,
        english: "Kainat",
        arabic: "کائنات",
        urdu: "کائنات",
        persian: "کائنات",
        meaning: "Universe, Creation",
        origin: "Urdu",
        pronunciation: "Kai-nat",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 52,
        english: "Mahnoor",
        arabic: "ماہ نور",
        urdu: "ماہ نور",
        persian: "ماه نور",
        meaning: "Moonlight, Radiant Face",
        origin: "Persian",
        pronunciation: "Mah-noor",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 53,
        english: "Naveed",
        arabic: "نوید",
        urdu: "نوید",
        persian: "نوید",
        meaning: "Good News, Glad Tidings",
        origin: "Persian",
        pronunciation: "Na-veed",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 54,
        english: "Omair",
        arabic: "عمير",
        urdu: "عمیر",
        persian: "عمیر",
        meaning: "Long-Lived, Intelligent",
        origin: "Arabic",
        pronunciation: "O-mair",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 55,
        english: "Pari",
        arabic: "پری",
        urdu: "پری",
        persian: "پری",
        meaning: "Fairy, Beautiful Being",
        origin: "Persian",
        pronunciation: "Pa-ri",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 56,
        english: "Qamar",
        arabic: "قمر",
        urdu: "قمر",
        persian: "قمر",
        meaning: "Moon, Radiant",
        origin: "Arabic",
        pronunciation: "Qa-mar",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 57,
        english: "Rameen",
        arabic: "رامین",
        urdu: "رامین",
        persian: "رامین",
        meaning: "Sunny, Joyful; Pleasant",
        origin: "Persian",
        pronunciation: "Ra-meen",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 58,
        english: "Saima",
        arabic: "صائمہ",
        urdu: "صائمہ",
        persian: "صائمه",
        meaning: "One who Fasts; Devout",
        origin: "Arabic",
        pronunciation: "Sai-ma",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 59,
        english: "Tahir",
        arabic: "طاہر",
        urdu: "طاہر",
        persian: "طاهر",
        meaning: "Pure, Chaste",
        origin: "Arabic",
        pronunciation: "Ta-hir",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 60,
        english: "Urooj",
        arabic: "عروج",
        urdu: "عروج",
        persian: "عروج",
        meaning: "Ascent, Rise, Elevation",
        origin: "Arabic",
        pronunciation: "U-rooj",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 61,
        english: "Yumna",
        arabic: "یمنہ",
        urdu: "یمنہ",
        persian: "یمنه",
        meaning: "Blessed, Auspicious",
        origin: "Arabic",
        pronunciation: "Yum-na",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 62,
        english: "Zahir",
        arabic: "ظاہر",
        urdu: "ظاہر",
        persian: "ظاهر",
        meaning: "Visible, Manifest; Brilliant",
        origin: "Arabic",
        pronunciation: "Za-hir",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 63,
        english: "Basma",
        arabic: "بسمة",
        urdu: "بسمة",
        persian: "بسمة",
        meaning: "Smile, Cheerful Countenance",
        origin: "Arabic",
        pronunciation: "Bas-ma",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 64,
        english: "Eimaan",
        arabic: "ایمان",
        urdu: "ایمان",
        persian: "ایمان",
        meaning: "Faith, Belief; Sincere Trust",
        origin: "Arabic",
        pronunciation: "Ei-maan",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 65,
        english: "Fawad",
        arabic: "فؤاد",
        urdu: "فواد",
        persian: "فواد",
        meaning: "Heart, Courageous Heart",
        origin: "Arabic",
        pronunciation: "Fa-wad",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 66,
        english: "Ghazanfar",
        arabic: "غضنفر",
        urdu: "غزنفر",
        persian: "غزنفر",
        meaning: "Lion, Brave Warrior",
        origin: "Persian",
        pronunciation: "Gha-zan-far",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 67,
        english: "Huma",
        arabic: "ہما",
        urdu: "ہما",
        persian: "هما",
        meaning: "Mythic Bird; Lucky, Benevolent",
        origin: "Persian",
        pronunciation: "Hu-ma",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 68,
        english: "Iklil",
        arabic: "إكلیل",
        urdu: "اکلیل",
        persian: "اکلیل",
        meaning: "Crown, Garland",
        origin: "Arabic",
        pronunciation: "Ik-lil",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 69,
        english: "Jumana",
        arabic: "جمانہ",
        urdu: "جمانہ",
        persian: "جمانه",
        meaning: "Silver Pearl, Precious",
        origin: "Arabic",
        pronunciation: "Ju-ma-na",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 70,
        english: "Kashan",
        arabic: "کاشان",
        urdu: "کاشان",
        persian: "کاشان",
        meaning: "From the City of Kashan; Beautiful Place",
        origin: "Persian",
        pronunciation: "Ka-shan",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 71,
        english: "Labeeb",
        arabic: "لبيب",
        urdu: "ل بیب",
        persian: "لبيب",
        meaning: "Sensible, Intelligent, Wise",
        origin: "Arabic",
        pronunciation: "La-beeb",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 72,
        english: "Mazin",
        arabic: "مزن",
        urdu: "مازن",
        persian: "مازن",
        meaning: "Proper Name; Strong and Glorious",
        origin: "Arabic",
        pronunciation: "Ma-zin",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 73,
        english: "Nayla",
        arabic: "نائلہ",
        urdu: "نایلہ",
        persian: "نایلا",
        meaning: "Attainer, Successful One",
        origin: "Arabic",
        pronunciation: "Nay-la",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 74,
        english: "Omaima",
        arabic: "امیمہ",
        urdu: "امیمہ",
        persian: "امیمه",
        meaning: "Little Mother; Gentle Care",
        origin: "Arabic",
        pronunciation: "O-mai-ma",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 75,
        english: "Parisa",
        arabic: "پاریسا",
        urdu: "پاریسا",
        persian: "پاریسا",
        meaning: "Like a Fairy, Elegant",
        origin: "Persian",
        pronunciation: "Pa-ri-sa",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 76,
        english: "Qudamah",
        arabic: "قدامة",
        urdu: "قدامہ",
        persian: "قدامه",
        meaning: "Bravery, Courageous",
        origin: "Arabic",
        pronunciation: "Qu-da-mah",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 77,
        english: "Rafi",
        arabic: "رفیع",
        urdu: "رفیع",
        persian: "رفیع",
        meaning: "Exalted, High, Noble",
        origin: "Arabic",
        pronunciation: "Ra-fi",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 78,
        english: "Salsabil",
        arabic: "سلسبیل",
        urdu: "سلسبیل",
        persian: "سلسبیل",
        meaning: "A Spring in Paradise, Pure Water",
        origin: "Arabic",
        pronunciation: "Sal-sa-bil",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 79,
        english: "Tahira",
        arabic: "طاهرة",
        urdu: "طاہرہ",
        persian: "طاهره",
        meaning: "Pure, Chaste, Virtuous",
        origin: "Arabic",
        pronunciation: "Ta-hi-ra",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 80,
        english: "Uzair",
        arabic: "عزیر",
        urdu: "عزیر",
        persian: "عزیر",
        meaning: "Helper; Mighty One (Ezra)",
        origin: "Arabic",
        pronunciation: "U-zair",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 81,
        english: "Widad",
        arabic: "وداد",
        urdu: "وداد",
        persian: "وداد",
        meaning: "Love, Affection, Friendship",
        origin: "Arabic",
        pronunciation: "Wi-dad",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 82,
        english: "Yara",
        arabic: "یارا",
        urdu: "یارا",
        persian: "یارا",
        meaning: "Beloved, Small Butterfly",
        origin: "Persian",
        pronunciation: "Ya-ra",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 83,
        english: "Zarmeen",
        arabic: "زرمین",
        urdu: "زرمین",
        persian: "زرمین",
        meaning: "Golden Land, Golden One",
        origin: "Persian",
        pronunciation: "Zar-meen",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 84,
        english: "Zunaira",
        arabic: "زنيّرة",
        urdu: "زنینہ",
        persian: "زنینه",
        meaning: "Guiding Light, Radiant",
        origin: "Arabic",
        pronunciation: "Zu-nai-ra",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 85,
        english: "Nawal",
        arabic: "نوال",
        urdu: "نوال",
        persian: "نوال",
        meaning: "Gift, Blessing",
        origin: "Arabic",
        pronunciation: "Na-wal",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 86,
        english: "Azlan",
        arabic: "أزلان",
        urdu: "ازلان",
        persian: "ازلان",
        meaning: "Lion, Brave",
        origin: "Arabic",
        pronunciation: "Az-lan",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 87,
        english: "Yasira",
        arabic: "يسيرة",
        urdu: "یسیرہ",
        persian: "یسیره",
        meaning: "Easy, Comfortable",
        origin: "Arabic",
        pronunciation: "Ya-si-ra",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 88,
        english: "Alina",
        arabic: "ألينا",
        urdu: "آلینا",
        persian: "آلینا",
        meaning: "Noble, Beautiful",
        origin: "Arabic",
        pronunciation: "A-li-na",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 89,
        english: "Alvira",
        arabic: "الفيرة",
        urdu: "الویرا",
        persian: "الویرا",
        meaning: "Truthful, Princess",
        origin: "Arabic",
        pronunciation: "Al-vi-ra",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 90,
        english: "Waseem",
        arabic: "وسيم",
        urdu: "وسیم",
        persian: "وسیم",
        meaning: "Handsome, Graceful",
        origin: "Arabic",
        pronunciation: "Wa-seem",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 91,
        english: "Arsalan",
        arabic: "أرسلان",
        urdu: "ارسلان",
        persian: "ارسلان",
        meaning: "Lion, Brave",
        origin: "Persian",
        pronunciation: "Ar-sa-lan",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 92,
        english: "Nimra",
        arabic: "نمرة",
        urdu: "نمرہ",
        persian: "نمره",
        meaning: "Princess, Pure",
        origin: "Arabic",
        pronunciation: "Nim-ra",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 93,
        english: "Danish",
        arabic: "دانش",
        urdu: "دانش",
        persian: "دانش",
        meaning: "Knowledge, Wisdom",
        origin: "Persian",
        pronunciation: "Da-nish",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 94,
        english: "Aizal",
        arabic: "أيزل",
        urdu: "ایزل",
        persian: "ایزل",
        meaning: "Precious, Valuable",
        origin: "Arabic",
        pronunciation: "Ai-zal",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 95,
        english: "Zoha",
        arabic: "زہى",
        urdu: "زوہا",
        persian: "زوها",
        meaning: "Light, Dawn",
        origin: "Arabic",
        pronunciation: "Zo-ha",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 96,
        english: "Amaan",
        arabic: "أمان",
        urdu: "امان",
        persian: "امان",
        meaning: "Peace, Safety",
        origin: "Arabic",
        pronunciation: "A-maan",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 97,
        english: "Inaya",
        arabic: "عناية",
        urdu: "عنایہ",
        persian: "عنایه",
        meaning: "Care, Concern",
        origin: "Arabic",
        pronunciation: "I-na-ya",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
        id: 98,
        english: "Shayan",
        arabic: "شايان",
        urdu: "شایان",
        persian: "شایان",
        meaning: "Worthy, Deserving",
        origin: "Persian",
        pronunciation: "Sha-yan",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 99,
        english: "Zaraq",
        arabic: "زراق",
        urdu: "زراق",
        persian: "زراق",
        meaning: "Shining, Bright",
        origin: "Arabic",
        pronunciation: "Za-raq",
        gender: "boy",
        status: "allowed",
        quranic: false
    },
    {
        id: 100,
        english: "Alizay",
        arabic: "عليزي",
        urdu: "علیزے",
        persian: "علیزای",
        meaning: "Princess, Noble",
        origin: "Arabic",
        pronunciation: "A-li-zay",
        gender: "girl",
        status: "allowed",
        quranic: false
    },
    {
    id: 101,
    english: "Rayyan",
    arabic: "ريان",
    urdu: "ریان",
    persian: "ریان",
    meaning: "Luxuriant, Full of Beauty",
    origin: "Arabic",
    pronunciation: "Rai-yaan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 102,
    english: "Zimal",
    arabic: "زمل",
    urdu: "زمل",
    persian: "زمل",
    meaning: "Garment, Covering",
    origin: "Arabic",
    pronunciation: "Zi-mal",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 103,
    english: "Farishta",
    arabic: "فريشتا",
    urdu: "فرشتہ",
    persian: "فرشته",
    meaning: "Angel, Divine Being",
    origin: "Persian",
    pronunciation: "Fa-rish-ta",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 104,
    english: "Shahzain",
    arabic: "شهزين",
    urdu: "شہزین",
    persian: "شهزین",
    meaning: "Royal Beauty, Crown",
    origin: "Persian",
    pronunciation: "Shah-zain",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 105,
    english: "Mehreen",
    arabic: "مهرين",
    urdu: "مہرین",
    persian: "مهرین",
    meaning: "Kindness, Affectionate",
    origin: "Persian",
    pronunciation: "Meh-reen",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 106,
    english: "Zavian",
    arabic: "زافيان",
    urdu: "زافیان",
    persian: "زافیان",
    meaning: "Bright, Shining",
    origin: "Arabic",
    pronunciation: "Za-vi-an",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 107,
    english: "Elan",
    arabic: "إيلان",
    urdu: "ایلان",
    persian: "ایلان",
    meaning: "Tree, Strong",
    origin: "Arabic",
    pronunciation: "Ei-lan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 108,
    english: "Zohaib",
    arabic: "زهيب",
    urdu: "زوہیب",
    persian: "زهیب",
    meaning: "Leader, Chief",
    origin: "Arabic",
    pronunciation: "Zo-haib",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 109,
    english: "Faryal",
    arabic: "فريال",
    urdu: "فریال",
    persian: "فریال",
    meaning: "Angel, Beautiful",
    origin: "Persian",
    pronunciation: "Far-yal",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 110,
    english: "Shanaya",
    arabic: "شانيا",
    urdu: "شانیہ",
    persian: "شانیا",
    meaning: "First Ray of Sun",
    origin: "Sanskrit",
    pronunciation: "Sha-na-ya",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 111,
    english: "Zorain",
    arabic: "زرين",
    urdu: "زرین",
    persian: "زرین",
    meaning: "Golden, Precious",
    origin: "Persian",
    pronunciation: "Zo-rain",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 112,
    english: "Mehak",
    arabic: "مهك",
    urdu: "مہک",
    persian: "مهک",
    meaning: "Fragrance, Sweet Smell",
    origin: "Persian",
    pronunciation: "Me-hak",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 113,
    english: "Shayaan",
    arabic: "شايان",
    urdu: "شایان",
    persian: "شایان",
    meaning: "Worthy, Deserving",
    origin: "Persian",
    pronunciation: "Sha-yaan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 114,
    english: "Zunash",
    arabic: "زنش",
    urdu: "زنش",
    persian: "زنش",
    meaning: "Beautiful Queen",
    origin: "Persian",
    pronunciation: "Zu-nash",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 115,
    english: "Rohaan",
    arabic: "روهان",
    urdu: "روحان",
    persian: "روحان",
    meaning: "Soulful, Spiritual",
    origin: "Persian",
    pronunciation: "Ro-haan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 116,
    english: "Fiza",
    arabic: "فضا",
    urdu: "فضا",
    persian: "فضا",
    meaning: "Atmosphere, Breeze",
    origin: "Arabic",
    pronunciation: "Fi-za",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 117,
    english: "Shahmeer",
    arabic: "شهمير",
    urdu: "شہمیر",
    persian: "شهمیر",
    meaning: "King of Peace",
    origin: "Persian",
    pronunciation: "Shah-meer",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 118,
    english: "Zaviyar",
    arabic: "زفيار",
    urdu: "زفیار",
    persian: "زفیار",
    meaning: "Light, Brightness",
    origin: "Persian",
    pronunciation: "Za-vi-yar",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 119,
    english: "Meher",
    arabic: "مهر",
    urdu: "مہر",
    persian: "مهر",
    meaning: "Sun, Kindness",
    origin: "Persian",
    pronunciation: "Me-her",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 120,
    english: "Shazain",
    arabic: "شازين",
    urdu: "شازین",
    persian: "شازین",
    meaning: "Princess, Royal",
    origin: "Persian",
    pronunciation: "Sha-zain",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 121,
    english: "Zoravar",
    arabic: "زوراور",
    urdu: "زوراور",
    persian: "زوراور",
    meaning: "Powerful, Strong",
    origin: "Persian",
    pronunciation: "Zo-ra-var",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 122,
    english: "Fareesha",
    arabic: "فريشا",
    urdu: "فریشا",
    persian: "فریشا",
    meaning: "Angel-like, Beautiful",
    origin: "Persian",
    pronunciation: "Fa-ree-sha",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 123,
    english: "Shahryar",
    arabic: "شهريار",
    urdu: "شہریار",
    persian: "شهریار",
    meaning: "Friend of City, King",
    origin: "Persian",
    pronunciation: "Shah-ryar",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 124,
    english: "Zohal",
    arabic: "زهال",
    urdu: "زوہل",
    persian: "زهال",
    meaning: "Saturn, Planet",
    origin: "Arabic",
    pronunciation: "Zo-hal",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 125,
    english: "Ruhan",
    arabic: "روهان",
    urdu: "روحان",
    persian: "روحان",
    meaning: "Spiritual, Soulful",
    origin: "Arabic",
    pronunciation: "Ru-han",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 126,
    english: "Faryaal",
    arabic: "فريال",
    urdu: "فریال",
    persian: "فریال",
    meaning: "Beautiful, Angelic",
    origin: "Persian",
    pronunciation: "Far-yaal",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 127,
    english: "Shahbaz",
    arabic: "شهباز",
    urdu: "شہباز",
    persian: "شهباز",
    meaning: "Royal Falcon, Brave",
    origin: "Persian",
    pronunciation: "Shah-baz",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 128,
    english: "Zaryab",
    arabic: "زارياب",
    urdu: "زاریاب",
    persian: "زاریاب",
    meaning: "Golden Water, Stream",
    origin: "Persian",
    pronunciation: "Za-ryab",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 129,
    english: "Mehran",
    arabic: "مهران",
    urdu: "مہران",
    persian: "مهران",
    meaning: "Kind, Compassionate",
    origin: "Persian",
    pronunciation: "Meh-ran",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 130,
    english: "Shahreen",
    arabic: "شهرين",
    urdu: "شہرین",
    persian: "شهرین",
    meaning: "City Dweller, Urban",
    origin: "Persian",
    pronunciation: "Shah-reen",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 131,
    english: "Zaryan",
    arabic: "زاريان",
    urdu: "زاریان",
    persian: "زاریان",
    meaning: "Golden Life, Precious",
    origin: "Persian",
    pronunciation: "Za-ryan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 132,
    english: "Fareed",
    arabic: "فريد",
    urdu: "فرید",
    persian: "فرید",
    meaning: "Unique, Incomparable",
    origin: "Arabic",
    pronunciation: "Fa-reed",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 133,
    english: "Mehroz",
    arabic: "مهراز",
    urdu: "مہروز",
    persian: "مهراز",
    meaning: "Sun-like, Radiant",
    origin: "Persian",
    pronunciation: "Meh-roz",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 134,
    english: "Zulnoor",
    arabic: "ذوالنور",
    urdu: "ذوالنور",
    persian: "ذوالنور",
    meaning: "Possessor of Light",
    origin: "Arabic",
    pronunciation: "Zul-noor",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 135,
    english: "Shahmir",
    arabic: "شهمير",
    urdu: "شہمیر",
    persian: "شهمیر",
    meaning: "King of Peace",
    origin: "Persian",
    pronunciation: "Shah-mir",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 136,
    english: "Fariha",
    arabic: "فريحة",
    urdu: "فریحہ",
    persian: "فریحه",
    meaning: "Happy, Joyful",
    origin: "Arabic",
    pronunciation: "Fa-ri-ha",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 137,
    english: "Zaviar",
    arabic: "زفيار",
    urdu: "زفیار",
    persian: "زفیار",
    meaning: "Bright, Shining",
    origin: "Persian",
    pronunciation: "Za-vi-ar",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 138,
    english: "Rohail",
    arabic: "رهيل",
    urdu: "روہیل",
    persian: "رهیل",
    meaning: "Wanderer, Traveler",
    origin: "Arabic",
    pronunciation: "Ro-hail",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 139,
    english: "Shahwar",
    arabic: "شهوار",
    urdu: "شہوار",
    persian: "شهوار",
    meaning: "King-like, Royal",
    origin: "Persian",
    pronunciation: "Shah-war",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 140,
    english: "Zunaira",
    arabic: "زنيّرة",
    urdu: "زنینہ",
    persian: "زنینه",
    meaning: "Guiding Light",
    origin: "Arabic",
    pronunciation: "Zu-nai-ra",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 141,
    english: "Fahad",
    arabic: "فهد",
    urdu: "فہد",
    persian: "فهد",
    meaning: "Lynx, Panther",
    origin: "Arabic",
    pronunciation: "Fa-had",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 142,
    english: "Meharban",
    arabic: "مهربان",
    urdu: "مہربان",
    persian: "مهربان",
    meaning: "Kind, Compassionate",
    origin: "Persian",
    pronunciation: "Me-har-ban",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 143,
    english: "Zorawar",
    arabic: "زوراور",
    urdu: "زوراور",
    persian: "زوراور",
    meaning: "Brave, Powerful",
    origin: "Persian",
    pronunciation: "Zo-ra-war",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 144,
    english: "Shahid",
    arabic: "شهيد",
    urdu: "شہید",
    persian: "شهید",
    meaning: "Witness, Martyr",
    origin: "Arabic",
    pronunciation: "Sha-hid",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 145,
    english: "Faraz",
    arabic: "فراز",
    urdu: "فراز",
    persian: "فراز",
    meaning: "Elevation, Ascent",
    origin: "Persian",
    pronunciation: "Fa-raz",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 146,
    english: "Zohaib",
    arabic: "زهيب",
    urdu: "زوہیب",
    persian: "زهیب",
    meaning: "Leader, Chief",
    origin: "Arabic",
    pronunciation: "Zo-haib",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 147,
    english: "Rohina",
    arabic: "روهينة",
    urdu: "روہینہ",
    persian: "روهینه",
    meaning: "Soulful, Spiritual",
    origin: "Persian",
    pronunciation: "Ro-hi-na",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 148,
    english: "Shahana",
    arabic: "شهانة",
    urdu: "شہانہ",
    persian: "شهانه",
    meaning: "Royal, Princess-like",
    origin: "Persian",
    pronunciation: "Sha-ha-na",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 149,
    english: "Zaryab",
    arabic: "زارياب",
    urdu: "زاریاب",
    persian: "زاریاب",
    meaning: "Golden Water",
    origin: "Persian",
    pronunciation: "Za-ryab",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 150,
    english: "Farihah",
    arabic: "فريحة",
    urdu: "فریحہ",
    persian: "فریحه",
    meaning: "Happy, Joyful",
    origin: "Arabic",
    pronunciation: "Fa-ri-hah",
    gender: "girl",
    status: "allowed",
    quranic: false
},
    {
    id: 151,
    english: "Aatif",
    arabic: "عاطف",
    urdu: "عاطف",
    persian: "عاطف",
    meaning: "Kind, Affectionate",
    origin: "Arabic",
    pronunciation: "Aa-tif",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 152,
    english: "Azhar",
    arabic: "أزهر",
    urdu: "ازہر",
    persian: "ازهر",
    meaning: "Shining, Luminous",
    origin: "Arabic",
    pronunciation: "Az-har",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 153,
    english: "Anwar",
    arabic: "أنور",
    urdu: "انور",
    persian: "انور",
    meaning: "Most Bright, Brilliant",
    origin: "Arabic",
    pronunciation: "An-war",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 154,
    english: "Asad",
    arabic: "أسد",
    urdu: "اسد",
    persian: "اسد",
    meaning: "Lion, Brave",
    origin: "Arabic",
    pronunciation: "A-sad",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 155,
    english: "Aslam",
    arabic: "أسلم",
    urdu: "اسلم",
    persian: "اسلم",
    meaning: "Very Safe, Protected",
    origin: "Arabic",
    pronunciation: "As-lam",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 156,
    english: "Asgar",
    arabic: "أصغر",
    urdu: "اصغر",
    persian: "اصغر",
    meaning: "Smallest, Youngest",
    origin: "Arabic",
    pronunciation: "As-gar",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 157,
    english: "Anees",
    arabic: "أنيس",
    urdu: "انیس",
    persian: "انیس",
    meaning: "Friendly, Companion",
    origin: "Arabic",
    pronunciation: "A-nees",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 158,
    english: "Akbar",
    arabic: "أكبر",
    urdu: "اکبر",
    persian: "اکبر",
    meaning: "Greatest, Honorable",
    origin: "Arabic",
    pronunciation: "Ak-bar",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 159,
    english: "Athar",
    arabic: "أثار",
    urdu: "اثار",
    persian: "اثار",
    meaning: "Pious, Pure",
    origin: "Arabic",
    pronunciation: "A-thar",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 160,
    english: "Ashfaaq",
    arabic: "أشفاق",
    urdu: "اشفاق",
    persian: "اشفاق",
    meaning: "Kindness, Compassion",
    origin: "Arabic",
    pronunciation: "Ash-faaq",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 161,
    english: "Ameen",
    arabic: "أمين",
    urdu: "امین",
    persian: "امین",
    meaning: "Trustworthy, Honest",
    origin: "Arabic",
    pronunciation: "A-meen",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 162,
    english: "Anjum",
    arabic: "أنجم",
    urdu: "انجم",
    persian: "انجم",
    meaning: "Stars, Constellations",
    origin: "Arabic",
    pronunciation: "An-jum",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 163,
    english: "Awais",
    arabic: "أويس",
    urdu: "اویس",
    persian: "اویس",
    meaning: "Gifted, Bestowed",
    origin: "Arabic",
    pronunciation: "A-wais",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 164,
    english: "Anas",
    arabic: "أنس",
    urdu: "انس",
    persian: "انس",
    meaning: "Friendly, Sociable",
    origin: "Arabic",
    pronunciation: "A-nas",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 165,
    english: "Amaan",
    arabic: "أمان",
    urdu: "امان",
    persian: "امان",
    meaning: "Safety, Security",
    origin: "Arabic",
    pronunciation: "A-maan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 166,
    english: "Akhlaq",
    arabic: "أخلاق",
    urdu: "اخلاق",
    persian: "اخلاق",
    meaning: "Good Morals, Ethics",
    origin: "Arabic",
    pronunciation: "Akh-laq",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 167,
    english: "Ameer",
    arabic: "أمير",
    urdu: "امیر",
    persian: "امیر",
    meaning: "Prince, Leader",
    origin: "Arabic",
    pronunciation: "A-meer",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 168,
    english: "Azmat",
    arabic: "عظمة",
    urdu: "عظمت",
    persian: "عظمت",
    meaning: "Greatness, Majesty",
    origin: "Arabic",
    pronunciation: "Az-mat",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 169,
    english: "Akram",
    arabic: "أكرم",
    urdu: "اکرم",
    persian: "اکرم",
    meaning: "Most Generous",
    origin: "Arabic",
    pronunciation: "Ak-ram",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 170,
    english: "Asim",
    arabic: "عاصم",
    urdu: "عاصم",
    persian: "عاصم",
    meaning: "Protector, Guardian",
    origin: "Arabic",
    pronunciation: "A-sim",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 171,
    english: "Arshad",
    arabic: "أرشد",
    urdu: "ارشاد",
    persian: "ارشاد",
    meaning: "Well Guided, Mature",
    origin: "Arabic",
    pronunciation: "Ar-shad",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 172,
    english: "Aahil",
    arabic: "عاهل",
    urdu: "عاہل",
    persian: "عاهل",
    meaning: "Prince, Emperor",
    origin: "Arabic",
    pronunciation: "Aa-hil",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 173,
    english: "Aalam",
    arabic: "عالم",
    urdu: "عالم",
    persian: "عالم",
    meaning: "World, Universe",
    origin: "Arabic",
    pronunciation: "Aa-lam",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 174,
    english: "Aalim",
    arabic: "عالم",
    urdu: "عالم",
    persian: "عالم",
    meaning: "Scholar, Knowledgeable",
    origin: "Arabic",
    pronunciation: "Aa-lim",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 175,
    english: "Aamil",
    arabic: "عامل",
    urdu: "عامل",
    persian: "عامل",
    meaning: "Doer, Worker",
    origin: "Arabic",
    pronunciation: "Aa-mil",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 176,
    english: "Aqib",
    arabic: "عقب",
    urdu: "عقب",
    persian: "عقب",
    meaning: "Successor, Follower",
    origin: "Arabic",
    pronunciation: "A-qib",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 177,
    english: "Aqil",
    arabic: "عاقل",
    urdu: "عاقل",
    persian: "عاقل",
    meaning: "Wise, Intelligent",
    origin: "Arabic",
    pronunciation: "A-qil",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 178,
    english: "Aarif",
    arabic: "عارف",
    urdu: "عارف",
    persian: "عارف",
    meaning: "Knowledgeable, Aware",
    origin: "Arabic",
    pronunciation: "Aa-rif",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 179,
    english: "Ariz",
    arabic: "عرض",
    urdu: "عرض",
    persian: "عرض",
    meaning: "Respectable, Honorable",
    origin: "Arabic",
    pronunciation: "A-riz",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 180,
    english: "Aaryan",
    arabic: "أريان",
    urdu: "اریان",
    persian: "اریان",
    meaning: "Noble, Warrior",
    origin: "Persian",
    pronunciation: "Aa-ryan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 181,
    english: "Aashif",
    arabic: "عاشف",
    urdu: "عاشف",
    persian: "عاشف",
    meaning: "Bold, Courageous",
    origin: "Arabic",
    pronunciation: "Aa-shif",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 182,
    english: "Aashir",
    arabic: "عاشر",
    urdu: "عاشر",
    persian: "عاشر",
    meaning: "Wealthy, Prosperous",
    origin: "Arabic",
    pronunciation: "Aa-shir",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 183,
    english: "Aasif",
    arabic: "عاصف",
    urdu: "عاصف",
    persian: "عاصف",
    meaning: "Stormy, Powerful",
    origin: "Arabic",
    pronunciation: "Aa-sif",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 184,
    english: "Aaus",
    arabic: "أوس",
    urdu: "اوس",
    persian: "اوس",
    meaning: "Gift, Benefit",
    origin: "Arabic",
    pronunciation: "A-aus",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 185,
    english: "Abaan",
    arabic: "أبان",
    urdu: "ابان",
    persian: "ابان",
    meaning: "Old Arabic Name",
    origin: "Arabic",
    pronunciation: "A-baan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 186,
    english: "Abbas",
    arabic: "عباس",
    urdu: "عباس",
    persian: "عباس",
    meaning: "Lion, Stern",
    origin: "Arabic",
    pronunciation: "Ab-bas",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 187,
    english: "Adeel",
    arabic: "عديل",
    urdu: "عدیل",
    persian: "عدیل",
    meaning: "Just, Fair",
    origin: "Arabic",
    pronunciation: "A-deel",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 188,
    english: "Adnan",
    arabic: "عدنان",
    urdu: "عدنان",
    persian: "عدنان",
    meaning: "Settler, Resident",
    origin: "Arabic",
    pronunciation: "Ad-nan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 189,
    english: "Affan",
    arabic: "عفان",
    urdu: "عفان",
    persian: "عفان",
    meaning: "Chaste, Modest",
    origin: "Arabic",
    pronunciation: "Af-fan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 190,
    english: "Ashaar",
    arabic: "أشعر",
    urdu: "اشعر",
    persian: "اشعر",
    meaning: "Poet, Perceptive",
    origin: "Arabic",
    pronunciation: "As-haar",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 191,
    english: "Ahsan",
    arabic: "أحسن",
    urdu: "احسن",
    persian: "احسن",
    meaning: "Best, Most Beautiful",
    origin: "Arabic",
    pronunciation: "Ah-san",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 192,
    english: "Arsalan",
    arabic: "أرسلان",
    urdu: "ارسلان",
    persian: "ارسلان",
    meaning: "Lion, Brave",
    origin: "Persian",
    pronunciation: "Ar-sa-lan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 193,
    english: "Ayaan",
    arabic: "أيان",
    urdu: "ایان",
    persian: "ایان",
    meaning: "Gift of God",
    origin: "Arabic",
    pronunciation: "Ay-aan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 194,
    english: "Azan",
    arabic: "أذان",
    urdu: "اذان",
    persian: "اذان",
    meaning: "Call to Prayer",
    origin: "Arabic",
    pronunciation: "A-zan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 195,
    english: "Afeef",
    arabic: "عفيف",
    urdu: "عفیف",
    persian: "عفیف",
    meaning: "Chaste, Virtuous",
    origin: "Arabic",
    pronunciation: "A-feef",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 196,
    english: "Aabid",
    arabic: "عابد",
    urdu: "عابد",
    persian: "عابد",
    meaning: "Worshipper, Devotee",
    origin: "Arabic",
    pronunciation: "Aa-bid",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 197,
    english: "Aadil",
    arabic: "عادل",
    urdu: "عادل",
    persian: "عادل",
    meaning: "Just, Fair",
    origin: "Arabic",
    pronunciation: "Aa-dil",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 198,
    english: "Aazim",
    arabic: "عازم",
    urdu: "عازم",
    persian: "عازم",
    meaning: "Determined, Resolute",
    origin: "Arabic",
    pronunciation: "Aa-zim",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 199,
    english: "Aaban",
    arabic: "أبان",
    urdu: "ابان",
    persian: "ابان",
    meaning: "Clear, Eloquent",
    origin: "Arabic",
    pronunciation: "Aa-ban",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 200,
    english: "Arif",
    arabic: "عارف",
    urdu: "عارف",
    persian: "عارف",
    meaning: "Knowledgeable, Wise",
    origin: "Arabic",
    pronunciation: "A-rif",
    gender: "boy",
    status: "allowed",
    quranic: false
},
    {
    id: 251,
    english: "Adnan",
    arabic: "عدنان",
    urdu: "عدنان",
    persian: "عدنان",
    meaning: "Settler, Resident",
    origin: "Arabic",
    pronunciation: "Ad-nan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 252,
    english: "Aflah",
    arabic: "أفلح",
    urdu: "افلح",
    persian: "افلح",
    meaning: "Successful",
    origin: "Arabic",
    pronunciation: "Af-lah",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 253,
    english: "Afraz",
    arabic: "افراز",
    urdu: "افراز",
    persian: "افراز",
    meaning: "Elevated, High",
    origin: "Persian",
    pronunciation: "Af-raz",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 254,
    english: "Afruz",
    arabic: "افروز",
    urdu: "افروز",
    persian: "افروز",
    meaning: "Illuminating",
    origin: "Persian",
    pronunciation: "Af-ruz",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 255,
    english: "Aftaab",
    arabic: "آفتاب",
    urdu: "آفتاب",
    persian: "آفتاب",
    meaning: "Sun, Bright",
    origin: "Persian",
    pronunciation: "Af-taab",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 256,
    english: "Aftab",
    arabic: "آفتاب",
    urdu: "آفتاب",
    persian: "آفتاب",
    meaning: "Sunshine",
    origin: "Persian",
    pronunciation: "Af-tab",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 257,
    english: "Agharr",
    arabic: "أغر",
    urdu: "اغر",
    persian: "اغر",
    meaning: "Handsome, Noble",
    origin: "Arabic",
    pronunciation: "Agh-arr",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 258,
    english: "Ahab",
    arabic: "آهب",
    urdu: "آہب",
    persian: "آهب",
    meaning: "Strong, Powerful",
    origin: "Arabic",
    pronunciation: "A-hab",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 259,
    english: "Ahmar",
    arabic: "أحمر",
    urdu: "احمر",
    persian: "احمر",
    meaning: "Red Colored",
    origin: "Arabic",
    pronunciation: "Ah-mar",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 260,
    english: "Ahnaf",
    arabic: "أحنف",
    urdu: "احنف",
    persian: "احنف",
    meaning: "Straight Path",
    origin: "Arabic",
    pronunciation: "Ah-naf",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 261,
    english: "Ahwas",
    arabic: "أحوص",
    urdu: "احوص",
    persian: "احوص",
    meaning: "Narrow-eyed",
    origin: "Arabic",
    pronunciation: "Ah-was",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 262,
    english: "Ahyan",
    arabic: "أحيان",
    urdu: "احیان",
    persian: "احیان",
    meaning: "Gift of God",
    origin: "Arabic",
    pronunciation: "Ah-yan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 263,
    english: "Ahzab",
    arabic: "أحزاب",
    urdu: "احزاب",
    persian: "احزاب",
    meaning: "Groups, Parties",
    origin: "Arabic",
    pronunciation: "Ah-zab",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 264,
    english: "Aidan",
    arabic: "عيدان",
    urdu: "عیدان",
    persian: "عیدان",
    meaning: "Helpful, Intelligent",
    origin: "Arabic",
    pronunciation: "Ai-dan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 265,
    english: "Aidh",
    arabic: "عائد",
    urdu: "عائد",
    persian: "عائد",
    meaning: "Returner, Reciter",
    origin: "Arabic",
    pronunciation: "A-idh",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 266,
    english: "Aijaz",
    arabic: "إعجاز",
    urdu: "اعجاز",
    persian: "اعجاز",
    meaning: "Miracle, Blessing",
    origin: "Arabic",
    pronunciation: "Ai-jaz",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 267,
    english: "Aiman",
    arabic: "أيمن",
    urdu: "ایمن",
    persian: "ایمن",
    meaning: "Fearless, Righteous",
    origin: "Arabic",
    pronunciation: "Ai-man",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 268,
    english: "Aizat",
    arabic: "عزة",
    urdu: "عزت",
    persian: "عزت",
    meaning: "Sweetness, Honor",
    origin: "Arabic",
    pronunciation: "Ai-zat",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 269,
    english: "Ajer",
    arabic: "أجر",
    urdu: "اجر",
    persian: "اجر",
    meaning: "Reward, Prize",
    origin: "Arabic",
    pronunciation: "A-jer",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 270,
    english: "Ajlah",
    arabic: "أجلة",
    urdu: "اجلہ",
    persian: "اجله",
    meaning: "Hadith Narrator",
    origin: "Arabic",
    pronunciation: "Aj-lah",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 271,
    english: "Ajmal",
    arabic: "أجمل",
    urdu: "اجمل",
    persian: "اجمل",
    meaning: "Most Beautiful",
    origin: "Arabic",
    pronunciation: "Aj-mal",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 272,
    english: "Akdas",
    arabic: "أقدس",
    urdu: "اقدس",
    persian: "اقدس",
    meaning: "Most Holy",
    origin: "Arabic",
    pronunciation: "Ak-das",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 273,
    english: "Akeem",
    arabic: "عقيم",
    urdu: "عقیم",
    persian: "عقیم",
    meaning: "Wise, Judge",
    origin: "Arabic",
    pronunciation: "A-keem",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 274,
    english: "Akhdan",
    arabic: "أخدان",
    urdu: "اخدان",
    persian: "اخدان",
    meaning: "Best Friend",
    origin: "Arabic",
    pronunciation: "Akh-dan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 275,
    english: "Akhfash",
    arabic: "أخفش",
    urdu: "اخفش",
    persian: "اخفش",
    meaning: "Grammarian",
    origin: "Arabic",
    pronunciation: "Akh-fash",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 276,
    english: "Akhtar",
    arabic: "أختر",
    urdu: "اختر",
    persian: "اختر",
    meaning: "Star, Good Man",
    origin: "Persian",
    pronunciation: "Akh-tar",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 277,
    english: "Akif",
    arabic: "عاكف",
    urdu: "عاکف",
    persian: "عاکف",
    meaning: "Attached, Devoted",
    origin: "Arabic",
    pronunciation: "A-kif",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 278,
    english: "Akmal",
    arabic: "أكمل",
    urdu: "اکمل",
    persian: "اکمل",
    meaning: "Perfect, Complete",
    origin: "Arabic",
    pronunciation: "Ak-mal",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 279,
    english: "Ala",
    arabic: "علا",
    urdu: "علا",
    persian: "علا",
    meaning: "Nobility, Excellence",
    origin: "Arabic",
    pronunciation: "A-la",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 280,
    english: "Alman",
    arabic: "ألمان",
    urdu: "المان",
    persian: "المان",
    meaning: "Kind, Wise",
    origin: "Arabic",
    pronunciation: "Al-man",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 281,
    english: "Almir",
    arabic: "ألمير",
    urdu: "المیر",
    persian: "المیر",
    meaning: "Prince, Noble",
    origin: "Arabic",
    pronunciation: "Al-mir",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 282,
    english: "Altamash",
    arabic: "ألتامش",
    urdu: "التامش",
    persian: "التامش",
    meaning: "Famous King",
    origin: "persian",
    pronunciation: "Al-ta-mash",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 283,
    english: "Amaar",
    arabic: "عمار",
    urdu: "عمار",
    persian: "عمار",
    meaning: "One Who Prays",
    origin: "Arabic",
    pronunciation: "A-maar",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 284,
    english: "Amam",
    arabic: "أمام",
    urdu: "امام",
    persian: "امام",
    meaning: "Safety, Protection",
    origin: "Arabic",
    pronunciation: "A-mam",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 285,
    english: "Amayr",
    arabic: "أمير",
    urdu: "امیر",
    persian: "امیر",
    meaning: "Crown, Prince",
    origin: "Arabic",
    pronunciation: "A-mayr",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 286,
    english: "Amer",
    arabic: "عامر",
    urdu: "عامر",
    persian: "عامر",
    meaning: "Rich, Prosperous",
    origin: "Arabic",
    pronunciation: "A-mer",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 287,
    english: "Amjad",
    arabic: "أمجد",
    urdu: "امجد",
    persian: "امجد",
    meaning: "More Glorious",
    origin: "Arabic",
    pronunciation: "Am-jad",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 288,
    english: "Ammaar",
    arabic: "عمار",
    urdu: "عمار",
    persian: "عمار",
    meaning: "Strong Faith",
    origin: "Arabic",
    pronunciation: "Am-maar",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 289,
    english: "Amr",
    arabic: "عمر",
    urdu: "عمر",
    persian: "عمر",
    meaning: "Long Life",
    origin: "Arabic",
    pronunciation: "Amr",
    gender: "boy",
    status: "allowed",
    quranic: false
},
    {
    id: 290,
    english: "Ashfaq",
    arabic: "أشفق",
    urdu: "اشفاق",
    persian: "اشفاق",
    meaning: "Compassionate Friend",
    origin: "Arabic",
    pronunciation: "Ash-faq",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 291,
    english: "Ashik",
    arabic: "عاشق",
    urdu: "عاشق",
    persian: "عاشق",
    meaning: "Lover, Devoted",
    origin: "Arabic",
    pronunciation: "A-shik",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 292,
    english: "Ashim",
    arabic: "عاشم",
    urdu: "عاشم",
    persian: "عاشم",
    meaning: "Generous, Noble",
    origin: "Arabic",
    pronunciation: "A-shim",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 293,
    english: "Ashmaan",
    arabic: "آسمان",
    urdu: "آسمان",
    persian: "آسمان",
    meaning: "Heaven, Sky",
    origin: "Persian",
    pronunciation: "Ash-maan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 294,
    english: "Ashmath",
    arabic: "أشمت",
    urdu: "اشمت",
    persian: "اشمت",
    meaning: "Straight Path",
    origin: "Arabic",
    pronunciation: "Ash-math",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 295,
    english: "Ashmirah",
    arabic: "أشميرة",
    urdu: "اشمیرہ",
    persian: "اشمیره",
    meaning: "Beautiful Princess",
    origin: "Arabic",
    pronunciation: "Ash-mi-rah",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 296,
    english: "Ashraf",
    arabic: "أشرف",
    urdu: "اشرف",
    persian: "اشرف",
    meaning: "Honorable, Noble",
    origin: "Arabic",
    pronunciation: "Ash-raf",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 297,
    english: "Asrar",
    arabic: "أسرار",
    urdu: "اسرار",
    persian: "اسرار",
    meaning: "Secrets, Mysteries",
    origin: "Arabic",
    pronunciation: "As-rar",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 298,
    english: "Ata",
    arabic: "عطاء",
    urdu: "عطا",
    persian: "عطا",
    meaning: "Gift, Present",
    origin: "Arabic",
    pronunciation: "A-ta",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 299,
    english: "Ataubaq",
    arabic: "عطوباق",
    urdu: "عطوباق",
    persian: "عطوباق",
    meaning: "Handsome, Generous",
    origin: "Arabic",
    pronunciation: "A-tau-baq",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 300,
    english: "Ateeb",
    arabic: "عتيب",
    urdu: "عتیب",
    persian: "عتیب",
    meaning: "Very Pious",
    origin: "Arabic",
    pronunciation: "A-teeb",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 301,
    english: "Athazaz",
    arabic: "أثازاز",
    urdu: "اثازاز",
    persian: "اثازاز",
    meaning: "Mystery, Enigma",
    origin: "Arabic",
    pronunciation: "Ath-a-zaz",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 302,
    english: "Athier",
    arabic: "أثير",
    urdu: "اثیر",
    persian: "اثیر",
    meaning: "Lion Hearted",
    origin: "Arabic",
    pronunciation: "Ath-ier",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 303,
    english: "Atik",
    arabic: "عتيق",
    urdu: "عتیق",
    persian: "عتیق",
    meaning: "Ancient, Noble",
    origin: "Arabic",
    pronunciation: "A-tik",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 304,
    english: "Atiq",
    arabic: "عتيق",
    urdu: "عتیق",
    persian: "عتیق",
    meaning: "Ancient, Classic",
    origin: "Arabic",
    pronunciation: "A-tiq",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 305,
    english: "Attiq",
    arabic: "عتق",
    urdu: "عتق",
    persian: "عتق",
    meaning: "Old, Ancient",
    origin: "Arabic",
    pronunciation: "At-tiq",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 306,
    english: "Awad",
    arabic: "عوض",
    urdu: "عوض",
    persian: "عوض",
    meaning: "Reward, Compensation",
    origin: "Arabic",
    pronunciation: "A-wad",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 307,
    english: "Awf",
    arabic: "عوف",
    urdu: "عوف",
    persian: "عوف",
    meaning: "Guest, Fragrance",
    origin: "Arabic",
    pronunciation: "Awf",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 308,
    english: "Awn",
    arabic: "عون",
    urdu: "عون",
    persian: "عون",
    meaning: "Help, Assistance",
    origin: "Arabic",
    pronunciation: "Awn",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 309,
    english: "Aws",
    arabic: "أوس",
    urdu: "اوس",
    persian: "اوس",
    meaning: "Gift, Bestowal",
    origin: "Arabic",
    pronunciation: "Aws",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 310,
    english: "Ayaaz",
    arabic: "أيعز",
    urdu: "ایاز",
    persian: "ایاز",
    meaning: "Sincere Slave",
    origin: "Persian",
    pronunciation: "Ay-aaz",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 311,
    english: "Ayaz",
    arabic: "أيعز",
    urdu: "ایاز",
    persian: "ایاز",
    meaning: "Loyal Servant",
    origin: "Persian",
    pronunciation: "Ay-az",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 312,
    english: "Aybak",
    arabic: "أيبك",
    urdu: "ایبک",
    persian: "ایبک",
    meaning: "Historical Figure",
    origin: "Turkish",
    pronunciation: "Ay-bak",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 313,
    english: "Aydin",
    arabic: "أيدين",
    urdu: "ایدین",
    persian: "ایدین",
    meaning: "Enlightened, Brilliant",
    origin: "Turkish",
    pronunciation: "Ay-din",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 314,
    english: "Aymaan",
    arabic: "أيمن",
    urdu: "ایمان",
    persian: "ایمان",
    meaning: "Lucky, Fortunate",
    origin: "Arabic",
    pronunciation: "Ay-maan",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 315,
    english: "Ayman",
    arabic: "أيمن",
    urdu: "ایمن",
    persian: "ایمن",
    meaning: "Right Hand, Blessed",
    origin: "Arabic",
    pronunciation: "Ay-man",
    gender: "girl",
    status: "allowed",
    quranic: false
},
{
    id: 316,
    english: "Ayyash",
    arabic: "عياش",
    urdu: "عیاش",
    persian: "عیاش",
    meaning: "Bread Seller",
    origin: "Arabic",
    pronunciation: "Ay-yash",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 317,
    english: "Azaan",
    arabic: "أذان",
    urdu: "اذان",
    persian: "اذان",
    meaning: "Call to Prayer",
    origin: "Arabic",
    pronunciation: "A-zaan",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 318,
    english: "Azad",
    arabic: "آزاد",
    urdu: "آزاد",
    persian: "آزاد",
    meaning: "Free, Independent",
    origin: "Persian",
    pronunciation: "A-zad",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 319,
    english: "Azam",
    arabic: "عظم",
    urdu: "عظم",
    persian: "عظم",
    meaning: "Great, Determined",
    origin: "Arabic",
    pronunciation: "A-zam",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 320,
    english: "Azeem",
    arabic: "عظيم",
    urdu: "عظیم",
    persian: "عظیم",
    meaning: "Great, Magnificent",
    origin: "Arabic",
    pronunciation: "A-zeem",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 321,
    english: "Azfer",
    arabic: "أظفر",
    urdu: "اظفر",
    persian: "اظفر",
    meaning: "Leader, Victorious",
    origin: "Arabic",
    pronunciation: "Az-fer",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 322,
    english: "Azim",
    arabic: "عظيم",
    urdu: "عظیم",
    persian: "عظیم",
    meaning: "Greatest, Supreme",
    origin: "Arabic",
    pronunciation: "A-zim",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 323,
    english: "Azmat",
    arabic: "عظمة",
    urdu: "عظمت",
    persian: "عظمت",
    meaning: "Respect, Honor",
    origin: "Arabic",
    pronunciation: "Az-mat",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 324,
    english: "Azraq",
    arabic: "أزرق",
    urdu: "ازرق",
    persian: "ازرق",
    meaning: "Blue Colored",
    origin: "Arabic",
    pronunciation: "Az-raq",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 325,
    english: "Azraqi",
    arabic: "أزرقى",
    urdu: "ازرقی",
    persian: "ازرقی",
    meaning: "Historian, Scholar",
    origin: "Arabic",
    pronunciation: "Az-ra-qi",
    gender: "boy",
    status: "allowed",
    quranic: false
},
{
    id: 326,
    english: "Azzam",
    arabic: "عزام",
    urdu: "عزام",
    persian: "عزام",
    meaning: "Determined, Resolute",
    origin: "Arabic",
    pronunciation: "Az-zam",
    gender: "boy",
    status: "allowed",
    quranic: false
},
    // ... continue with remaining names
];
