const quranicNames = [
    {
        id: 1,
        english: "Muhammad",
        arabic: "محمد",
        urdu: "محمد",
        persian: "محمد",
        meaning: "Praised, Praiseworthy",
        origin: "Arabic",
        pronunciation: "Moo-ham-mad",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah Al-Imran 3:144"
    },
    {
        id: 2,
        english: "Ibrahim",
        arabic: "إبراهيم",
        urdu: "ابراہیم",
        persian: "ابراهیم",
        meaning: "Father of Many",
        origin: "Arabic",
        pronunciation: "Ib-raa-heem",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah Al-Baqarah 2:124"
    },
    {
        id: 3,
        english: "Yusuf",
        arabic: "يوسف",
        urdu: "یوسف",
        persian: "یوسف",
        meaning: "God Will Increase",
        origin: "Arabic",
        pronunciation: "Yoo-soof",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah Yusuf 12:4"
    },
    {
        id: 4,
        english: "Maryam",
        arabic: "مريم",
        urdu: "مریم",
        persian: "مریم",
        meaning: "Beloved, Pure",
        origin: "Arabic",
        pronunciation: "Mar-yam",
        gender: "girl",
        status: "allowed",
        quranic: true,
        ayah: "Surah Maryam 19:16"
    },
    {
        id: 5,
        english: "Musa",
        arabic: "موسى",
        urdu: "موسیٰ",
        persian: "موسی",
        meaning: "Drawn Out of Water",
        origin: "Arabic",
        pronunciation: "Moo-saa",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah Taha 20:9"
    },
    {
        id: 6,
        english: "Isa",
        arabic: "عيسى",
        urdu: "عیسیٰ",
        persian: "عیسی",
        meaning: "God is Salvation",
        origin: "Arabic",
        pronunciation: "Ee-saa",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah Al-Imran 3:45"
    },
    {
        id: 7,
        english: "Yunus",
        arabic: "يونس",
        urdu: "یونس",
        persian: "یونس",
        meaning: "Dove",
        origin: "Arabic",
        pronunciation: "Yoo-noos",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah Yunus 10:98"
    },
    {
        id: 8,
        english: "Zakariya",
        arabic: "زكريا",
        urdu: "زکریا",
        persian: "زکریا",
        meaning: "God Remembers",
        origin: "Arabic",
        pronunciation: "Za-ka-ree-ya",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah Maryam 19:2"
    },
    {
        id: 9,
        english: "Adam",
        arabic: "آدم",
        urdu: "آدم",
        persian: "آدم",
        meaning: "First Man, Earth",
        origin: "Arabic",
        pronunciation: "Aa-dam",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah Al-Baqarah 2:31"
    },
    {
        id: 10,
        english: "Idris",
        arabic: "إدريس",
        urdu: "ادریس",
        persian: "ادریس",
        meaning: "Interpreter, Teacher",
        origin: "Arabic",
        pronunciation: "Id-rees",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah Maryam 19:56"
    },
    {
        id: 11,
        english: "Haroon",
        arabic: "هارون",
        urdu: "ہارون",
        persian: "هارون",
        meaning: "Messenger, Prophet",
        origin: "Arabic",
        pronunciation: "Haa-roon",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah Maryam 19:53"
    },
    {
        id: 12,
        english: "Sulaiman",
        arabic: "سليمان",
        urdu: "سلیمان",
        persian: "سلیمان",
        meaning: "Man of Peace",
        origin: "Arabic",
        pronunciation: "Su-lai-maan",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah Al-Baqarah 2:102"
    },
    {
        id: 13,
        english: "Dawud",
        arabic: "داود",
        urdu: "داؤد",
        persian: "داوود",
        meaning: "Beloved, Friend",
        origin: "Arabic",
        pronunciation: "Daa-wood",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah Al-Baqarah 2:251"
    },
    {
        id: 14,
        english: "Yahya",
        arabic: "يحيى",
        urdu: "یحییٰ",
        persian: "یحیی",
        meaning: "God is Gracious",
        origin: "Arabic",
        pronunciation: "Yah-ya",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah Maryam 19:7"
    },
    {
        id: 15,
        english: "Ismail",
        arabic: "إسماعيل",
        urdu: "اسماعیل",
        persian: "اسماعیل",
        meaning: "God Will Hear",
        origin: "Arabic",
        pronunciation: "Is-maa-eel",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah Maryam 19:54"
    },
    {
        id: 16,
        english: "Yaqoob",
        arabic: "يعقوب",
        urdu: "یعقوب",
        persian: "یعقوب",
        meaning: "Supplanter, Holder of Heel",
        origin: "Arabic",
        pronunciation: "Yaa-qoob",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah Al-Baqarah 2:132"
    },
    {
        id: 17,
        english: "Luqman",
        arabic: "لقمان",
        urdu: "لقمان",
        persian: "لقمان",
        meaning: "Wise Man",
        origin: "Arabic",
        pronunciation: "Luq-maan",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah Luqman 31:12"
    },
    {
        id: 18,
        english: "Tariq",
        arabic: "طارق",
        urdu: "طارق",
        persian: "طارق",
        meaning: "Morning Star, Knocker",
        origin: "Arabic",
        pronunciation: "Taa-riq",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah At-Tariq 86:1"
    },
    {
        id: 19,
        english: "Noor",
        arabic: "نور",
        urdu: "نور",
        persian: "نور",
        meaning: "Light, Illumination",
        origin: "Arabic",
        pronunciation: "Noor",
        gender: "girl",
        status: "allowed",
        quranic: true,
        ayah: "Surah An-Nur 24:35"
    },
    {
        id: 20,
        english: "Jannat",
        arabic: "جنة",
        urdu: "جنت",
        persian: "جنت",
        meaning: "Paradise, Garden",
        origin: "Arabic",
        pronunciation: "Jan-nat",
        gender: "girl",
        status: "allowed",
        quranic: true,
        ayah: "Surah Al-Baqarah 2:25"
    },
    {
        id: 21,
        english: "Rayyan",
        arabic: "ريّان",
        urdu: "ریان",
        persian: "ریان",
        meaning: "Gate of Paradise for Fasting People",
        origin: "Arabic",
        pronunciation: "Ray-yan",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Sahih Muslim 1152"
    },
    {
        id: 22,
        english: "Abrar",
        arabic: "أبرار",
        urdu: "ابرار",
        persian: "ابرار",
        meaning: "Pious, Righteous",
        origin: "Arabic",
        pronunciation: "Ab-rar",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah Al-Insan 76:5"
    },
    {
        id: 23,
        english: "Firdaus",
        arabic: "فردوس",
        urdu: "فردوس",
        persian: "فردوس",
        meaning: "Highest Garden in Paradise",
        origin: "Arabic",
        pronunciation: "Fir-daus",
        gender: "girl",
        status: "allowed",
        quranic: true,
        ayah: "Surah Al-Kahf 18:107"
    },
    {
        id: 24,
        english: "Mubeen",
        arabic: "مبين",
        urdu: "مبین",
        persian: "مبین",
        meaning: "Clear, Manifest",
        origin: "Arabic",
        pronunciation: "Mu-been",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah An-Nur 24:1"
    },
    {
        id: 25,
        english: "Shahid",
        arabic: "شهيد",
        urdu: "شہید",
        persian: "شهید",
        meaning: "Witness, Martyr",
        origin: "Arabic",
        pronunciation: "Sha-hid",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah Al-Baqarah 2:143"
    },
    {
        id: 26,
        english: "Zimal",
        arabic: "زمل",
        urdu: "زمل",
        persian: "زمل",
        meaning: "Garment, Covering",
        origin: "Arabic",
        pronunciation: "Zi-mal",
        gender: "girl",
        status: "allowed",
        quranic: true,
        ayah: "Surah Al-A'raf 7:26"
    },
    {
        id: 27,
        english: "Nuh",
        arabic: "نوح",
        urdu: "نوح",
        persian: "نوح",
        meaning: "Prophet Noah",
        origin: "Arabic",
        pronunciation: "Nooh",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah Nuh 71:1"
    },
    {
        id: 28,
        english: "Hud",
        arabic: "هود",
        urdu: "ہود",
        persian: "هود",
        meaning: "Prophet Hud",
        origin: "Arabic",
        pronunciation: "Hood",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah Hud 11:50"
    },
    {
        id: 29,
        english: "Salih",
        arabic: "صالح",
        urdu: "صالح",
        persian: "صالح",
        meaning: "Prophet Salih",
        origin: "Arabic",
        pronunciation: "Sa-lih",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah Ash-Shu'ara 26:142"
    },
    {
        id: 30,
        english: "Shuaib",
        arabic: "شعيب",
        urdu: "شعیب",
        persian: "شعیب",
        meaning: "Prophet Shuaib",
        origin: "Arabic",
        pronunciation: "Shu-aib",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah Al-A'raf 7:85"
    },
    {
        id: 31,
        english: "Ayyub",
        arabic: "أيوب",
        urdu: "ایوب",
        persian: "ایوب",
        meaning: "Prophet Job",
        origin: "Arabic",
        pronunciation: "Ay-yoob",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah An-Nisa 4:163"
    },
    {
        id: 32,
        english: "Ayat",
        arabic: "آيات",
        urdu: "آیات",
        persian: "آیات",
        meaning: "Signs of God, Quranic Verses",
        origin: "Arabic",
        pronunciation: "A-yat",
        gender: "girl",
        status: "allowed",
        quranic: true,
        ayah: "Surah Fussilat 41:53"
    },
    {
        id: 33,
        english: "Barakah",
        arabic: "بركة",
        urdu: "برکت",
        persian: "برکت",
        meaning: "Blessing, Abundance",
        origin: "Arabic",
        pronunciation: "Ba-ra-kah",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah Al-A'raf 7:96"
    },
    {
        id: 34,
        english: "Fajar",
        arabic: "فجر",
        urdu: "فجر",
        persian: "فجر",
        meaning: "Dawn, Morning",
        origin: "Arabic",
        pronunciation: "Fa-jar",
        gender: "girl",
        status: "allowed",
        quranic: true,
        ayah: "Surah Al-Fajr 89:1"
    },
    {
        id: 35,
        english: "Hadi",
        arabic: "هادي",
        urdu: "ہادی",
        persian: "هادی",
        meaning: "Guide, Leader",
        origin: "Arabic",
        pronunciation: "Ha-di",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah Al-Furqan 25:31"
    },
    {
        id: 36,
        english: "Iman",
        arabic: "إيمان",
        urdu: "ایمان",
        persian: "ایمان",
        meaning: "Faith, Belief",
        origin: "Arabic",
        pronunciation: "I-man",
        gender: "girl",
        status: "allowed",
        quranic: true,
        ayah: "Surah Al-Hujurat 49:7"
    },
    {
        id: 37,
        english: "Kawthar",
        arabic: "كوثر",
        urdu: "کوثر",
        persian: "کوثر",
        meaning: "Abundance, River in Paradise",
        origin: "Arabic",
        pronunciation: "Kaw-thar",
        gender: "girl",
        status: "allowed",
        quranic: true,
        ayah: "Surah Al-Kawthar 108:1"
    },
    {
        id: 38,
        english: "Lut",
        arabic: "لوط",
        urdu: "لوط",
        persian: "لوط",
        meaning: "Prophet Lot",
        origin: "Arabic",
        pronunciation: "Loot",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah Ash-Shu'ara 26:160"
    },
    {
        id: 39,
        english: "Yaseen",
        arabic: "يٰسٓ",
        urdu: "یٰسٓ",
        persian: "یٰسٓ",
        meaning: "Chapter of Quran",
        origin: "Arabic",
        pronunciation: "Ya-seen",
        gender: "boy",
        status: "allowed",
        quranic: true,
        ayah: "Surah Ya-Sin 36:1"
    }
];
